microsoft/RD-Agent

.readthedocs.yaml, requirements/docs.txt
----
📚 Documentation preview 📚: https://RDAgent--204.org.readthedocs.build/en/204/
=> docs: fix build docs error

README.md, docs/ui.rst
----
📚 Documentation preview 📚: https://RDAgent--206.org.readthedocs.build/en/206/
=> docs: Fix log path example

README.md
Update README with a link to the scen documentation.
----
📚 Documentation preview 📚: https://RDAgent--205.org.readthedocs.build/en/205/
=> docs: Update README with a link to the scen documentation.

rdagent/core/conf.py, rdagent/scenarios/qlib/factor_experiment_loader/pdf_loader.py, rdagent/scenarios/qlib/factor_experiment_loader/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--210.org.readthedocs.build/en/210/
=> feat: add relevance check to quant factors

rdagent/utils/env.py
----
📚 Documentation preview 📚: https://RDAgent--215.org.readthedocs.build/en/215/
=> feat: add progress status for docker env

rdagent/core/conf.py, rdagent/scenarios/qlib/factor_experiment_loader/pdf_loader.py
Fix some bugs in llm calling.
----
📚 Documentation preview 📚: https://RDAgent--217.org.readthedocs.build/en/217/
=> fix: fix some bugs in llm calling

rdagent/scenarios/qlib/docker/Dockerfile
mlflow 1.30.0 requires numpy<2
pyqlib 0.9.5.99 requires numpy<1.24,>=1.12.0
numpy 1.23.5 will be installed after `RUN python -m pip install -e .`
----
📚 Documentation preview 📚: https://RDAgent--177.org.readthedocs.build/en/177/
=> fix: remove useless line

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/documentation.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/question.md, README.md, docs/conf.py, docs/index.rst
----
📚 Documentation preview 📚: https://RDAgent--208.org.readthedocs.build/en/208/
=> docs: add badge & Github button & issue template

rdagent/components/document_reader/document_reader.py, requirements.txt
----
📚 Documentation preview 📚: https://RDAgent--234.org.readthedocs.build/en/234/
=> fix: package dependency.

docs/development.rst
----
📚 Documentation preview 📚: https://RDAgent--235.org.readthedocs.build/en/235/
=> docs: Update development.rst

README.md, docs/scens/model_agent_med.rst
----
📚 Documentation preview 📚: https://RDAgent--248.org.readthedocs.build/en/248/
=> fix: readme

README.md, docs/scens/data_copilot_fin.rst, docs/scens/model_agent_fin.rst, docs/scens/model_agent_med.rst, docs/scens/model_copilot_general.rst
Updated:
- demo traces download link in README.md
- demo video links in docs
----
📚 Documentation preview 📚: https://RDAgent--251.org.readthedocs.build/en/251/
=> docs: links update

README.md
----
📚 Documentation preview 📚: https://RDAgent--253.org.readthedocs.build/en/253/
=> docs: Update Link to Papers & Qlib

README.md, rdagent/core/conf.py
----
📚 Documentation preview 📚: https://RDAgent--256.org.readthedocs.build/en/256/
=> fix: default model value in config

rdagent/app/cli.py, rdagent/app/general_model/general_model.py, rdagent/components/benchmark/conf.py, rdagent/components/runner/conf.py, rdagent/core/conf.py
----
📚 Documentation preview 📚: https://RDAgent--257.org.readthedocs.build/en/257/
=> fix: fix_dotenv_error

rdagent/scenarios/qlib/proposal/factor_proposal.py
----
📚 Documentation preview 📚: https://RDAgent--261.org.readthedocs.build/en/261/
=> fix: rdagent factor bug when FactorTask init

rdagent/log/ui/app.py, rdagent/scenarios/kaggle/experiment/meta_tpl/model/model_xgb.py, rdagent/scenarios/kaggle/experiment/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--266.org.readthedocs.build/en/266/
=> fix: a bug in ui app & modify prompts for kaggle loop

rdagent/app/cli.py, rdagent/app/kaggle/loop.py
----
📚 Documentation preview 📚: https://RDAgent--271.org.readthedocs.build/en/271/
=> feat: add kaggle command

rdagent/app/kaggle/loop.py, rdagent/scenarios/kaggle/experiment/scenario.py, rdagent/scenarios/kaggle/proposal/proposal.py
----
📚 Documentation preview 📚: https://RDAgent--273.org.readthedocs.build/en/273/
=> fix: fix a small bug in kaggle scenario caused by the second RAG update

rdagent/scenarios/kaggle/experiment/meta_tpl/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/workspace.py
Refine the code.
----
📚 Documentation preview 📚: https://RDAgent--276.org.readthedocs.build/en/276/
=> fix: refine the code

rdagent/scenarios/kaggle/developer/runner.py
----
📚 Documentation preview 📚: https://RDAgent--282.org.readthedocs.build/en/282/
=> fix: Update runner.py to fix a small bug

rdagent/scenarios/kaggle/developer/feedback.py, rdagent/scenarios/kaggle/prompts.yaml
This is to support all actions in the feedback process. 
Supposedly this should improve the performance overall. 
----
📚 Documentation preview 📚: https://RDAgent--280.org.readthedocs.build/en/280/
=> feat: Feature selection v3 to support all actions 

rdagent/scenarios/kaggle/experiment/prompts.yaml
Refine the prompt.
----
📚 Documentation preview 📚: https://RDAgent--286.org.readthedocs.build/en/286/
=> fix: refine the prompt

rdagent/utils/env.py, test/utils/test_env.py
----
📚 Documentation preview 📚: https://RDAgent--290.org.readthedocs.build/en/290/
=> fix: support memory limit

rdagent/scenarios/kaggle/developer/feedback.py, rdagent/scenarios/kaggle/experiment/prompts.yaml, rdagent/scenarios/kaggle/prompts.yaml
Fix some bugs in feedback.py and refine the prompt.
----
📚 Documentation preview 📚: https://RDAgent--292.org.readthedocs.build/en/292/
=> fix: fix some bugs in feedback.py and refine the prompt

rdagent/scenarios/kaggle/experiment/forest-cover-type-prediction_template/cross_validation.py
----
📚 Documentation preview 📚: https://RDAgent--295.org.readthedocs.build/en/295/
=> fix: edit a file path

test/utils/test_kaggle.py
----
📚 Documentation preview 📚: https://RDAgent--296.org.readthedocs.build/en/296/
=> fix: test kaggle method

rdagent/scenarios/kaggle/experiment/workspace.py, rdagent/utils/env.py
----
📚 Documentation preview 📚: https://RDAgent--297.org.readthedocs.build/en/297/
=> fix: kaggle data mount problem

rdagent/scenarios/kaggle/developer/runner.py
----
📚 Documentation preview 📚: https://RDAgent--299.org.readthedocs.build/en/299/
=> fix: debugging for model

rdagent/components/coder/factor_coder/CoSTEER/__init__.py, rdagent/components/coder/factor_coder/CoSTEER/evolving_strategy.py, rdagent/components/coder/factor_coder/CoSTEER/knowledge_management.py, rdagent/components/coder/factor_coder/config.py, rdagent/components/coder/factor_coder/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--294.org.readthedocs.build/en/294/
=> feat: Factor Implement Search Enhancement

rdagent/app/benchmark/factor/analysis.py, rdagent/components/benchmark/eval_method.py, rdagent/components/coder/factor_coder/factor.py, rdagent/components/coder/model_coder/model.py, rdagent/core/experiment.py, rdagent/scenarios/qlib/factor_experiment_loader/json_loader.py
----
📚 Documentation preview 📚: https://RDAgent--302.org.readthedocs.build/en/302/
=> fix: refactor Bench

rdagent/components/coder/model_coder/CoSTEER/evolving_strategy.py, rdagent/components/coder/model_coder/model.py
----
📚 Documentation preview 📚: https://RDAgent--303.org.readthedocs.build/en/303/
=> fix: update code to fix a small bug in model cache md5 hash

rdagent/components/coder/factor_coder/CoSTEER/__init__.py, rdagent/components/coder/factor_coder/CoSTEER/evolving_strategy.py, rdagent/components/coder/factor_coder/CoSTEER/knowledge_management.py, rdagent/components/coder/factor_coder/config.py, rdagent/components/coder/factor_coder/prompts.yaml
This reverts commit 4ecf25f0acf2389a172b14d3dab20895daf2ab89.
----
📚 Documentation preview 📚: https://RDAgent--305.org.readthedocs.build/en/305/
=> revert: Revert feat: Factor Implement Search Enhancement (#294)

rdagent/scenarios/kaggle/experiment/playground-series-s3e26_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e26_template/feature/feature.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e26_template/model/model_randomforest.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e26_template/model/model_xgboost.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e26_template/train.py
----
📚 Documentation preview 📚: https://RDAgent--308.org.readthedocs.build/en/308/
=> feat: template for kaggle

rdagent/app/kaggle/conf.py, rdagent/scenarios/kaggle/developer/feedback.py, rdagent/scenarios/kaggle/developer/runner.py, rdagent/scenarios/kaggle/experiment/forest-cover-type-prediction_template/model/model_randomforest.py, rdagent/scenarios/kaggle/experiment/forest-cover-type-prediction_template/model/model_xgboost.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e26_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e26_template/feature/feature.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e26_template/model/model_randomforest.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e26_template/model/model_xgboost.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e26_template/train.py, rdagent/scenarios/kaggle/experiment/prompts.yaml, rdagent/scenarios/kaggle/experiment/scenario.py, rdagent/scenarios/kaggle/proposal/proposal.py, rdagent/scenarios/qlib/experiment/factor_experiment.py, rdagent/scenarios/qlib/experiment/prompts.yaml
Add qlib_factor_strategy
----
📚 Documentation preview 📚: https://RDAgent--307.org.readthedocs.build/en/307/
=> feat: add qlib_factor_strategy

rdagent/log/ui/app.py
----
📚 Documentation preview 📚: https://RDAgent--313.org.readthedocs.build/en/313/
=> fix: raise error in demo when no Metric in a Loop

rdagent/components/coder/factor_coder/factor.py, rdagent/scenarios/kaggle/experiment/forest-cover-type-prediction_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/meta_tpl/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e8_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e9_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/scenario.py, rdagent/scenarios/kaggle/experiment/sf-crime_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/spaceship-titanic_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/workspace.py
----
📚 Documentation preview 📚: https://RDAgent--314.org.readthedocs.build/en/314/
=> fix: align local data folder and kaggle data folder to store mid result

rdagent/log/ui/app.py
----
📚 Documentation preview 📚: https://RDAgent--317.org.readthedocs.build/en/317/
=> feat: add download submission.csv button for kaggle scenario

rdagent/scenarios/kaggle/experiment/sf-crime_template/model/model_nn.py
----
📚 Documentation preview 📚: https://RDAgent--318.org.readthedocs.build/en/318/
=> fix: a bug in kaggle experiment models

rdagent/scenarios/kaggle/proposal/proposal.py, rdagent/utils/workflow.py
Change the mechanism of traceback and action choosing.
----
📚 Documentation preview 📚: https://RDAgent--320.org.readthedocs.build/en/320/
=> feat: change the mechanism of traceback and action choosing

rdagent/scenarios/kaggle/experiment/playground-series-s3e11_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e11_template/feature/feature.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e11_template/model/model_xgboost.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e11_template/train.py, rdagent/utils/env.py
----
📚 Documentation preview 📚: https://RDAgent--324.org.readthedocs.build/en/324/
=> feat: add s3e11 kaggle template

rdagent/utils/env.py
----
📚 Documentation preview 📚: https://RDAgent--326.org.readthedocs.build/en/326/
=> feat: change docker logs print

rdagent/scenarios/kaggle/experiment/forest-cover-type-prediction_template/train.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e11_template/train.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e26_template/train.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e8_template/train.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e9_template/train.py, rdagent/scenarios/kaggle/experiment/sf-crime_template/train.py, rdagent/scenarios/kaggle/experiment/spaceship-titanic_template/train.py
Fix a bug in the format of the model input.
----
📚 Documentation preview 📚: https://RDAgent--327.org.readthedocs.build/en/327/
=> fix: fix a bug in the format of the model input

rdagent/scenarios/kaggle/developer/runner.py, rdagent/scenarios/kaggle/experiment/scenario.py, rdagent/scenarios/kaggle/experiment/workspace.py
----
📚 Documentation preview 📚: https://RDAgent--329.org.readthedocs.build/en/329/
=> fix: use factor setting in kaggle scenario

rdagent/components/coder/factor_coder/CoSTEER/evaluators.py, rdagent/scenarios/kaggle/experiment/scenario.py
----
📚 Documentation preview 📚: https://RDAgent--332.org.readthedocs.build/en/332/
=> fix: avoid_generating_more_column_than_data

rdagent/scenarios/kaggle/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--333.org.readthedocs.build/en/333/
=> fix: fix a bug in feature selection prompt

rdagent/utils/env.py
----
📚 Documentation preview 📚: https://RDAgent--336.org.readthedocs.build/en/336/
=> fix: stop using markup in docker env print

rdagent/scenarios/kaggle/experiment/prompts.yaml, rdagent/scenarios/kaggle/experiment/scenario.py
----
📚 Documentation preview 📚: https://RDAgent--337.org.readthedocs.build/en/337/
=> fix: multi channel support in kaggle scenario (revised version)

rdagent/scenarios/kaggle/prompts.yaml
Fix a bug in model tuning feedback.
----
📚 Documentation preview 📚: https://RDAgent--339.org.readthedocs.build/en/339/
=> fix: fix a bug in model tuning feedback

rdagent/scenarios/kaggle/developer/runner.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e8_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e8_template/train.py
----
📚 Documentation preview 📚: https://RDAgent--338.org.readthedocs.build/en/338/
=> fix: a bug of developer& edit s4e8 template

rdagent/scenarios/kaggle/developer/runner.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e8_template/model/model_randomforest.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e8_template/model/model_xgboost.py, rdagent/scenarios/kaggle/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--341.org.readthedocs.build/en/341/
=> fix: Update prompts.yaml to constrain only one model type  

rdagent/app/kaggle/conf.py, rdagent/scenarios/kaggle/experiment/scenario.py, rdagent/scenarios/kaggle/prompts.yaml, rdagent/scenarios/kaggle/proposal/proposal.py
Add a button to control feature selection.
----
📚 Documentation preview 📚: https://RDAgent--342.org.readthedocs.build/en/342/
=> feat: add a button to control feature selection

rdagent/app/kaggle/conf.py, rdagent/app/kaggle/loop.py
----
📚 Documentation preview 📚: https://RDAgent--345.org.readthedocs.build/en/345/
=> feat: auto submit result after one kaggle RDLoop

rdagent/log/ui/app.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e8_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e8_template/train.py
----
📚 Documentation preview 📚: https://RDAgent--348.org.readthedocs.build/en/348/
=> feat: show workspace in demo

rdagent/app/kaggle/loop.py
----
📚 Documentation preview 📚: https://RDAgent--349.org.readthedocs.build/en/349/
=> fix: catch submission exception

rdagent/scenarios/kaggle/developer/feedback.py, rdagent/scenarios/kaggle/experiment/prompts.yaml, rdagent/scenarios/kaggle/experiment/scenario.py, rdagent/scenarios/kaggle/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--346.org.readthedocs.build/en/346/
=> feat: better feedback & evaluation

rdagent/scenarios/kaggle/experiment/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--352.org.readthedocs.build/en/352/
=> fix: remove temp debug prompt

rdagent/scenarios/kaggle/experiment/playground-series-s3e11_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e8_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e8_template/model/model_xgboost.py, rdagent/scenarios/kaggle/experiment/spaceship-titanic_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/spaceship-titanic_template/model/model_nn.py, rdagent/scenarios/kaggle/experiment/spaceship-titanic_template/model/model_xgboost.py
----
📚 Documentation preview 📚: https://RDAgent--358.org.readthedocs.build/en/358/
=> fix: preprocess output format & some mistake in spelling

rdagent/scenarios/kaggle/proposal/proposal.py
Fix a typo.
----
📚 Documentation preview 📚: https://RDAgent--362.org.readthedocs.build/en/362/
=> fix: fix a typo

rdagent/components/coder/factor_coder/CoSTEER/evaluators.py
----
📚 Documentation preview 📚: https://RDAgent--363.org.readthedocs.build/en/363/
=> fix: undefined error for evaluator

rdagent/components/coder/factor_coder/CoSTEER/evaluators.py
Fix a bug in code costeer.
----
📚 Documentation preview 📚: https://RDAgent--373.org.readthedocs.build/en/373/
=> fix: fix a bug in code costeer

rdagent/scenarios/kaggle/experiment/digit-recognizer_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/digit-recognizer_template/feature/feature.py, rdagent/scenarios/kaggle/experiment/digit-recognizer_template/model/model_xgboost.py, rdagent/scenarios/kaggle/experiment/digit-recognizer_template/model/select_xgboost.py, rdagent/scenarios/kaggle/experiment/digit-recognizer_template/train.py
----
📚 Documentation preview 📚: https://RDAgent--375.org.readthedocs.build/en/375/
=> feat: supporting Mnist competition

rdagent/scenarios/kaggle/experiment/covid19-global-forecasting-week-1_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/covid19-global-forecasting-week-1_template/feature/feature.py, rdagent/scenarios/kaggle/experiment/covid19-global-forecasting-week-1_template/model/model_xgboost.py, rdagent/scenarios/kaggle/experiment/covid19-global-forecasting-week-1_template/model/select_xgboost.py, rdagent/scenarios/kaggle/experiment/covid19-global-forecasting-week-1_template/train.py, rdagent/scenarios/kaggle/knowledge_management/vector_base.py, rdagent/scenarios/kaggle/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--374.org.readthedocs.build/en/374/
=> feat: Supporting COVID-19 competition

rdagent/scenarios/kaggle/experiment/digit-recognizer_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e8_template/train.py
Fix two templates.
----
📚 Documentation preview 📚: https://RDAgent--376.org.readthedocs.build/en/376/
=> fix: fix two templates

rdagent/app/kaggle/loop.py, rdagent/core/knowledge_base.py, rdagent/scenarios/kaggle/experiment/digit-recognizer_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/digit-recognizer_template/model/model_nn.py, rdagent/scenarios/kaggle/experiment/digit-recognizer_template/model/select_nn.py, rdagent/scenarios/kaggle/experiment/digit-recognizer_template/train.py
Fix some bugs in knowledge base.
----
📚 Documentation preview 📚: https://RDAgent--378.org.readthedocs.build/en/378/
=> fix: fix some bugs in knowledge base

rdagent/app/kaggle/loop.py
----
📚 Documentation preview 📚: https://RDAgent--379.org.readthedocs.build/en/379/
=> fix: Quick fixes for logging

rdagent/scenarios/kaggle/knowledge_management/vector_base.py
----
📚 Documentation preview 📚: https://RDAgent--380.org.readthedocs.build/en/380/
=> fix: debug vector base

rdagent/app/benchmark/factor/analysis.py, rdagent/components/benchmark/eval_method.py, rdagent/components/coder/factor_coder/CoSTEER/evaluators.py, rdagent/components/coder/factor_coder/factor.py, rdagent/core/experiment.py
----
📚 Documentation preview 📚: https://RDAgent--369.org.readthedocs.build/en/369/
=> feat: cache exception

rdagent/app/kaggle/loop.py
----
📚 Documentation preview 📚: https://RDAgent--384.org.readthedocs.build/en/384/
=> feat: can convert covid workspace to merged.py for submission

rdagent/scenarios/kaggle/developer/feedback.py, rdagent/scenarios/kaggle/experiment/scenario.py, rdagent/scenarios/kaggle/knowledge_management/vector_base.py
----
📚 Documentation preview 📚: https://RDAgent--385.org.readthedocs.build/en/385/
=> fix: rag save file

rdagent/components/coder/factor_coder/factor.py
----
📚 Documentation preview 📚: https://RDAgent--383.org.readthedocs.build/en/383/
=> fix: cache

rdagent/scenarios/kaggle/experiment/scenario.py
----
📚 Documentation preview 📚: https://RDAgent--388.org.readthedocs.build/en/388/
=> fix: fix a bug in scenario.py

rdagent/app/kaggle/conf.py, rdagent/scenarios/kaggle/experiment/scenario.py, rdagent/scenarios/kaggle/kaggle_crawler.py, rdagent/scenarios/kaggle/knowledge_management/vector_base.py, rdagent/scenarios/kaggle/prompts.yaml, rdagent/scenarios/kaggle/proposal/proposal.py
Fix a bug in mini case.
----
📚 Documentation preview 📚: https://RDAgent--389.org.readthedocs.build/en/389/
=> fix: fix a bug in mini case

rdagent/scenarios/kaggle/prompts.yaml, rdagent/scenarios/kaggle/proposal/proposal.py
Revise to support better hypothesis proposal  (make it more granular)
----
📚 Documentation preview 📚: https://RDAgent--390.org.readthedocs.build/en/390/
=> feat: Revise to support better hypothesis proposal 

rdagent/scenarios/kaggle/experiment/playground-series-s3e14_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e14_template/feature/feature.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e14_template/model/model_randomforest.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e14_template/model/model_xgboost.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e14_template/model/select_randomforest.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e14_template/model/select_xgboost.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e14_template/train.py
----
📚 Documentation preview 📚: https://RDAgent--394.org.readthedocs.build/en/394/
=> feat: add kaggle s3e14 template

rdagent/scenarios/kaggle/kaggle_crawler.py
----
📚 Documentation preview 📚: https://RDAgent--397.org.readthedocs.build/en/397/
=> feat: get competition scores list

rdagent/scenarios/kaggle/developer/coder.py, rdagent/scenarios/kaggle/experiment/covid19-global-forecasting-week-1_template/model/select_xgboost.py, rdagent/scenarios/kaggle/experiment/digit-recognizer_template/model/select_nn.py, rdagent/scenarios/kaggle/experiment/digit-recognizer_template/model/select_xgboost.py, rdagent/scenarios/kaggle/experiment/feedback-prize-english-language-learning_template/model/select_randomforest.py, rdagent/scenarios/kaggle/experiment/feedback-prize-english-language-learning_template/model/select_xgboost.py, rdagent/scenarios/kaggle/experiment/forest-cover-type-prediction_template/model/select_nn.py, rdagent/scenarios/kaggle/experiment/forest-cover-type-prediction_template/model/select_randomforest.py, rdagent/scenarios/kaggle/experiment/forest-cover-type-prediction_template/model/select_xgboost.py, rdagent/scenarios/kaggle/experiment/optiver-realized-volatility-prediction_template/model/select_randomforest.py, rdagent/scenarios/kaggle/experiment/optiver-realized-volatility-prediction_template/model/select_xgboost.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e11_template/model/select_randomforest.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e11_template/model/select_xgboost.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e26_template/model/select_randomforest.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e26_template/model/select_xgboost.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e8_template/model/select_randomforest.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e8_template/model/select_xgboost.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e9_template/model/select_randomforest.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e9_template/model/select_xgboost.py, rdagent/scenarios/kaggle/experiment/sf-crime_template/model/select_randomforest.py, rdagent/scenarios/kaggle/experiment/sf-crime_template/model/select_xgboost.py, rdagent/scenarios/kaggle/experiment/spaceship-titanic_template/model/select_nn.py, rdagent/scenarios/kaggle/experiment/spaceship-titanic_template/model/select_randomforest.py, rdagent/scenarios/kaggle/experiment/spaceship-titanic_template/model/select_xgboost.py, rdagent/scenarios/kaggle/experiment/statoil-iceberg-classifier-challenge_template/model/select_xgboost.py
Fix bug when flatten MultiIndex columns of features dataframe in feature selection.
----
📚 Documentation preview 📚: https://RDAgent--398.org.readthedocs.build/en/398/
=> fix: bug in kaggle feature selection

rdagent/log/ui/web.py
seperate -> separate
----
📚 Documentation preview 📚: https://RDAgent--395.org.readthedocs.build/en/395/
=> chore: update web.py

rdagent/scenarios/kaggle/developer/feedback.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e8_template/model/model_randomforest.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e8_template/model/model_xgboost.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e8_template/train.py, rdagent/scenarios/kaggle/experiment/scenario.py, rdagent/scenarios/kaggle/kaggle_crawler.py, rdagent/scenarios/kaggle/prompts.yaml, rdagent/scenarios/kaggle/proposal/proposal.py
Add ranking in kaggle scenario.
----
📚 Documentation preview 📚: https://RDAgent--401.org.readthedocs.build/en/401/
=> feat: Add ranking in kaggle scenario

rdagent/scenarios/kaggle/experiment/digit-recognizer_template/train.py, rdagent/scenarios/kaggle/experiment/forest-cover-type-prediction_template/train.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e8_template/train.py, rdagent/scenarios/kaggle/experiment/spaceship-titanic_template/train.py
----
📚 Documentation preview 📚: https://RDAgent--403.org.readthedocs.build/en/403/
=> fix: name of index

rdagent/scenarios/kaggle/kaggle_crawler.py
----
📚 Documentation preview 📚: https://RDAgent--405.org.readthedocs.build/en/405/
=> feat: find rank in leaderboard

rdagent/scenarios/kaggle/developer/feedback.py, rdagent/scenarios/kaggle/experiment/prompts.yaml, rdagent/scenarios/kaggle/proposal/proposal.py
Refine the ucb algorithm.
----
📚 Documentation preview 📚: https://RDAgent--406.org.readthedocs.build/en/406/
=> fix: refine the ucb algorithm

rdagent/app/kaggle/conf.py, rdagent/core/knowledge_base.py, rdagent/scenarios/kaggle/experiment/prompts.yaml, rdagent/scenarios/kaggle/experiment/scenario.py
Fix a bug in competition metric evaluation.
----
📚 Documentation preview 📚: https://RDAgent--407.org.readthedocs.build/en/407/
=> fix: fix a bug in competition metric evaluation

rdagent/log/ui/app.py
----
📚 Documentation preview 📚: https://RDAgent--410.org.readthedocs.build/en/410/
=> feat: show execution time in demo

rdagent/core/conf.py, rdagent/oai/llm_utils.py, rdagent/scenarios/qlib/factor_experiment_loader/pdf_loader.py
----
📚 Documentation preview 📚: https://RDAgent--415.org.readthedocs.build/en/415/
=> perf: use main thread to get embedding to speed up cache

rdagent/components/coder/factor_coder/CoSTEER/evaluators.py, rdagent/components/coder/factor_coder/CoSTEER/knowledge_management.py
1. when facing odd v2_query_component_limit, make from gt bigger than without gt
2. do code evaluator even value does not pass
3. provide the value header to value failed evaluators
----
📚 Documentation preview 📚: https://RDAgent--417.org.readthedocs.build/en/417/
=> perf: improve factor costeer

rdagent/core/experiment.py, rdagent/utils/env.py
----
📚 Documentation preview 📚: https://RDAgent--386.org.readthedocs.build/en/386/
=> fix: fix json load error

rdagent/scenarios/kaggle/kaggle_crawler.py
----
📚 Documentation preview 📚: https://RDAgent--423.org.readthedocs.build/en/423/
=> fix: auto select html element of text contents in kaggle crawler now

rdagent/components/coder/factor_coder/CoSTEER/evaluators.py
Using the `bool()` function will cause any non-empty string (including `false`) to be converted to `True`.
----
📚 Documentation preview 📚: https://RDAgent--428.org.readthedocs.build/en/428/
=> fix: convert str to bool

rdagent/components/coder/factor_coder/CoSTEER/evaluators.py, rdagent/scenarios/qlib/factor_experiment_loader/json_loader.py
----
📚 Documentation preview 📚: https://RDAgent--432.org.readthedocs.build/en/432/
=> fix: force use_chat_cache False when facing error in evaluators

rdagent/core/utils.py
----
📚 Documentation preview 📚: https://RDAgent--434.org.readthedocs.build/en/434/
=> chore: number of subprocesses <= number of tasks

rdagent/log/storage.py
----
📚 Documentation preview 📚: https://RDAgent--437.org.readthedocs.build/en/437/
=> fix: bug of reading log file tags on Windows

rdagent/log/ui/app.py
----
📚 Documentation preview 📚: https://RDAgent--440.org.readthedocs.build/en/440/
=> fix: display bug of GeneralModelScenario in webapp

constraints/3.10.txt, constraints/3.11.txt, rdagent/components/coder/model_coder/CoSTEER/evaluators.py, rdagent/components/coder/model_coder/model_execute_template_v1.txt, rdagent/components/coder/model_coder/model_execute_template_v2.txt, requirements.txt, test/utils/test_import.py
----
📚 Documentation preview 📚: https://RDAgent--439.org.readthedocs.build/en/439/
=> chore: remove torch in main code

constraints/3.10.txt, constraints/3.11.txt, requirements.txt
----
📚 Documentation preview 📚: https://RDAgent--447.org.readthedocs.build/en/447/
=> chore: remove package

docs/scens/catalog.rst, docs/scens/kaggle_agent.rst, rdagent/app/kaggle/conf.py
Add documentation for Kaggle scenario.
----
📚 Documentation preview 📚: https://RDAgent--448.org.readthedocs.build/en/448/
=> docs: add documentation for kaggle scen

rdagent/scenarios/kaggle/developer/runner.py
----
📚 Documentation preview 📚: https://RDAgent--451.org.readthedocs.build/en/451/
=> fix: method about KGFactorRunner cache system

rdagent/components/coder/factor_coder/CoSTEER/evaluators.py
`feedback_str` should be a string; otherwise, the operation `conclusion_str = "\n".join(conclusions)` may fail
----
📚 Documentation preview 📚: https://RDAgent--453.org.readthedocs.build/en/453/
=> fix: feedback_str

rdagent/scenarios/kaggle/experiment/digit-recognizer_template/model/model_nn.py
----
📚 Documentation preview 📚: https://RDAgent--456.org.readthedocs.build/en/456/
=> fix: templates bug

docs/scens/catalog.rst
----
📚 Documentation preview 📚: https://RDAgent--458.org.readthedocs.build/en/458/
=> docs: edit catalog

rdagent/app/kaggle/conf.py, rdagent/app/kaggle/loop.py
Fix a bug in `kaggle conf`.
----
📚 Documentation preview 📚: https://RDAgent--459.org.readthedocs.build/en/459/
=> fix: fix a bug in kaggle conf

constraints/3.10.txt, constraints/3.11.txt, rdagent/app/kaggle/conf.py, rdagent/core/exception.py, rdagent/scenarios/kaggle/kaggle_crawler.py
----
📚 Documentation preview 📚: https://RDAgent--464.org.readthedocs.build/en/464/
=> fix: unzip kaggle data

rdagent/scenarios/kaggle/kaggle_crawler.py
----
📚 Documentation preview 📚: https://RDAgent--470.org.readthedocs.build/en/470/
=> fix: a bug in zip file crawler in kaggle

rdagent/app/kaggle/conf.py, rdagent/components/coder/model_coder/model.py, rdagent/scenarios/kaggle/developer/runner.py, rdagent/scenarios/kaggle/experiment/scenario.py, rdagent/scenarios/kaggle/kaggle_crawler.py, rdagent/scenarios/kaggle/prompts.yaml, rdagent/scenarios/kaggle/proposal/proposal.py
End-to-end optimization.
----
📚 Documentation preview 📚: https://RDAgent--473.org.readthedocs.build/en/473/
=> feat: end-to-end optimization

README.md, docs/scens/kaggle_agent.rst
Fix a bug in the document.
----
📚 Documentation preview 📚: https://RDAgent--466.org.readthedocs.build/en/466/
=> docs: fix a bug in the document

README.md
----
📚 Documentation preview 📚: https://RDAgent--478.org.readthedocs.build/en/478/
=> docs: fix url in docs

rdagent/scenarios/kaggle/experiment/tabular-playground-series-may-2022_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/tabular-playground-series-may-2022_template/feature/feature.py, rdagent/scenarios/kaggle/experiment/tabular-playground-series-may-2022_template/model/model_randomforest.py, rdagent/scenarios/kaggle/experiment/tabular-playground-series-may-2022_template/model/model_xgboost.py, rdagent/scenarios/kaggle/experiment/tabular-playground-series-may-2022_template/model/select_nn.py, rdagent/scenarios/kaggle/experiment/tabular-playground-series-may-2022_template/model/select_randomforest.py, rdagent/scenarios/kaggle/experiment/tabular-playground-series-may-2022_template/model/select_xgboost.py, rdagent/scenarios/kaggle/experiment/tabular-playground-series-may-2022_template/train.py
Only xgboost & randomforest model now.
----
📚 Documentation preview 📚: https://RDAgent--481.org.readthedocs.build/en/481/
=> feat: (Kaggle) add base template for competition: tabular-playground-series-may-2022

rdagent/scenarios/kaggle/experiment/ventilator-pressure-prediction_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/ventilator-pressure-prediction_template/feature/feature.py, rdagent/scenarios/kaggle/experiment/ventilator-pressure-prediction_template/model/model_randomforest.py, rdagent/scenarios/kaggle/experiment/ventilator-pressure-prediction_template/model/model_xgboost.py, rdagent/scenarios/kaggle/experiment/ventilator-pressure-prediction_template/model/select_nn.py, rdagent/scenarios/kaggle/experiment/ventilator-pressure-prediction_template/model/select_randomforest.py, rdagent/scenarios/kaggle/experiment/ventilator-pressure-prediction_template/model/select_xgboost.py, rdagent/scenarios/kaggle/experiment/ventilator-pressure-prediction_template/train.py
xgboost&randomforest
----
📚 Documentation preview 📚: https://RDAgent--482.org.readthedocs.build/en/482/
=> feat: (kaggle) add base template of competition: ventilator-pressure-prediction

rdagent/scenarios/kaggle/experiment/tabular-playground-series-dec-2021_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/tabular-playground-series-dec-2021_template/model/model_xgboost.py, rdagent/scenarios/kaggle/experiment/tabular-playground-series-dec-2021_template/train.py
----
📚 Documentation preview 📚: https://RDAgent--484.org.readthedocs.build/en/484/
=> feat: template changes for some kaggle competitions

rdagent/scenarios/kaggle/experiment/new-york-city-taxi-fare-prediction_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/new-york-city-taxi-fare-prediction_template/feature/feature.py, rdagent/scenarios/kaggle/experiment/new-york-city-taxi-fare-prediction_template/model/model_randomforest.py, rdagent/scenarios/kaggle/experiment/new-york-city-taxi-fare-prediction_template/model/model_xgboost.py, rdagent/scenarios/kaggle/experiment/new-york-city-taxi-fare-prediction_template/model/select_lightgbm.py, rdagent/scenarios/kaggle/experiment/new-york-city-taxi-fare-prediction_template/model/select_nn.py, rdagent/scenarios/kaggle/experiment/new-york-city-taxi-fare-prediction_template/model/select_randomforest.py, rdagent/scenarios/kaggle/experiment/new-york-city-taxi-fare-prediction_template/model/select_xgboost.py, rdagent/scenarios/kaggle/experiment/new-york-city-taxi-fare-prediction_template/train.py, rdagent/scenarios/kaggle/experiment/tabular-playground-series-dec-2021_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/workspace.py, rdagent/utils/env.py, test/utils/test_kaggle.py
----
📚 Documentation preview 📚: https://RDAgent--485.org.readthedocs.build/en/485/
=> Add tpl: new-york-city-taxi-fare-prediction_template

rdagent/oai/llm_utils.py
----
📚 Documentation preview 📚: https://RDAgent--494.org.readthedocs.build/en/494/
=> fix: patching weird azure deployment

rdagent/oai/llm_utils.py
----
📚 Documentation preview 📚: https://RDAgent--496.org.readthedocs.build/en/496/
=> fix: a fix to resume llama3 and phi models

rdagent/components/coder/model_coder/eva_utils.py, rdagent/components/coder/model_coder/evaluators.py, rdagent/components/coder/model_coder/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--501.org.readthedocs.build/en/501/
=> fix: a bug in model coder final feedback

rdagent/scenarios/qlib/experiment/model_template/conf.yaml
----
📚 Documentation preview 📚: https://RDAgent--503.org.readthedocs.build/en/503/
=> fix: a default conf in scen qlib

rdagent/oai/llm_utils.py
----
📚 Documentation preview 📚: https://RDAgent--509.org.readthedocs.build/en/509/
=> fix: avoid warning for missing llama installation when not in use

rdagent/scenarios/qlib/developer/factor_runner.py
----
📚 Documentation preview 📚: https://RDAgent--514.org.readthedocs.build/en/514/
=> fix: ignore failed implementation

rdagent/oai/backend/base.py, rdagent/oai/llm_conf.py
The current `litellm_backend` branch is behind the `ds_refactor` branch. To avoid future conflicts with `ds_refactor`, this PR merges partial changes from the `ds_refactor` branch into the `litellm_backend` branch. In other words, the goal of this change is to ensure that the `litellm_backend` branch can be implemented based on the latest updates from the `ds_refactor` branch.
- **Background**: The `litellm_backend` branch is currently behind the `ds_refactor` branch, which may lead to conflicts in the future.
- **Solution**: By merging partial changes from the `ds_refactor` branch, this PR ensures that the `litellm_backend` branch stays in sync with the `ds_refactor` branch, avoiding potential conflicts.
=> fix(litellm_backend): merge ds_refactor changes

pyproject.toml, rdagent/app/kaggle/loop.py, rdagent/app/qlib_rd_loop/factor_from_report.py, rdagent/components/coder/factor_coder/eva_utils.py, rdagent/components/workflow/rd_loop.py, rdagent/core/evolving_agent.py, rdagent/log/storage.py, rdagent/log/ui/app.py, rdagent/scenarios/data_mining/proposal/model_proposal.py, rdagent/scenarios/data_science/proposal/prompts.yaml, rdagent/scenarios/kaggle/developer/feedback.py, rdagent/scenarios/kaggle/experiment/scenario.py, rdagent/scenarios/kaggle/prompts.yaml, rdagent/scenarios/kaggle/proposal/proposal.py, rdagent/scenarios/qlib/prompts.yaml, rdagent/scenarios/qlib/proposal/factor_proposal.py, rdagent/scenarios/qlib/proposal/model_proposal.py, rdagent/utils/env.py, rdagent/utils/workflow.py
----
📚 Documentation preview 📚: https://RDAgent--523.org.readthedocs.build/en/523/
=> test: Test ds refactor ll

rdagent/app/data_science/loop.py
Fix a small bug in data science loop
----
📚 Documentation preview 📚: https://RDAgent--524.org.readthedocs.build/en/524/
=> fix: fix a small bug

rdagent/scenarios/data_science/proposal/exp_gen.py, rdagent/scenarios/data_science/proposal/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--527.org.readthedocs.build/en/527/
=> fix: avoid generating same prompt in exp_gen

rdagent/scenarios/data_science/dev/runner.py
----
📚 Documentation preview 📚: https://RDAgent--528.org.readthedocs.build/en/528/
=> chore: clean unused scripts

rdagent/components/coder/data_science/feature/eval_tests/feature_test.txt
----
📚 Documentation preview 📚: https://RDAgent--531.org.readthedocs.build/en/531/
=> fix: minor bug in feature test

rdagent/components/coder/data_science/raw_data_loader/prompts.yaml, rdagent/scenarios/data_science/dev/runner.py
----
📚 Documentation preview 📚: https://RDAgent--532.org.readthedocs.build/en/532/
=> fix: inject code bug and improve dataloader spec code

rdagent/log/ui/dsapp.py
----
📚 Documentation preview 📚: https://RDAgent--536.org.readthedocs.build/en/536/
=> fix: ui on new log trace of data science scenario

rdagent/utils/env.py
----
📚 Documentation preview 📚: https://RDAgent--537.org.readthedocs.build/en/537/
=> feat: add configurable volume mode for Docker volumes in env.py

rdagent/app/data_science/loop.py, rdagent/log/mle_summary.py
----
📚 Documentation preview 📚: https://RDAgent--540.org.readthedocs.build/en/540/
=> fix: score bug and refine restart strategy

rdagent/components/coder/data_science/ensemble/eval_tests/ensemble_test.txt, rdagent/components/coder/data_science/raw_data_loader/prompts.yaml, rdagent/scenarios/kaggle/tpl_ex/aerial-cactus-identification/ensemble.py, rdagent/scenarios/kaggle/tpl_ex/aerial-cactus-identification/main.py, rdagent/scenarios/kaggle/tpl_ex/aerial-cactus-identification/spec/ensemble.md
----
📚 Documentation preview 📚: https://RDAgent--541.org.readthedocs.build/en/541/
=> chore: rename ens_and_decision

rdagent/components/coder/data_science/workflow/eval_tests/submission_check.txt
----
📚 Documentation preview 📚: https://RDAgent--542.org.readthedocs.build/en/542/
=> feat: dynamically find and use sample submission file in eval tests

rdagent/log/mle_summary.py
----
📚 Documentation preview 📚: https://RDAgent--543.org.readthedocs.build/en/543/
=> fix: mle_summary loop_num count

rdagent/components/coder/data_science/workflow/eval_tests/submission_check.txt, rdagent/utils/env.py
----
📚 Documentation preview 📚: https://RDAgent--544.org.readthedocs.build/en/544/
=> fix: fix submission file search and add TODO in env.py

rdagent/components/coder/data_science/workflow/eval.py, rdagent/components/coder/data_science/workflow/eval_tests/mle_submission_check.txt, rdagent/scenarios/data_science/dev/runner.py
----
📚 Documentation preview 📚: https://RDAgent--545.org.readthedocs.build/en/545/
=> feat: add mlebench submission validitor

rdagent/components/coder/data_science/feature/eval_tests/feature_test.txt, rdagent/scenarios/data_science/proposal/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--546.org.readthedocs.build/en/546/
=> fix: refine prompt to generate the most simple task in init stage

rdagent/components/coder/data_science/ensemble/eval.py, rdagent/components/coder/data_science/feature/eval.py, rdagent/components/coder/data_science/model/eval.py, rdagent/components/coder/data_science/raw_data_loader/eval.py, rdagent/components/coder/data_science/workflow/eval.py, rdagent/core/exception.py, rdagent/utils/agent/__init__.py, rdagent/utils/agent/workflow.py
----
📚 Documentation preview 📚: https://RDAgent--548.org.readthedocs.build/en/548/
=> fix: replace API call with build_cls_from_json_with_retry function

rdagent/app/cli.py, rdagent/components/coder/data_science/model/eval.py, rdagent/components/coder/data_science/raw_data_loader/__init__.py, rdagent/core/proposal.py, rdagent/log/ui/dsapp.py, rdagent/scenarios/kaggle/experiment/templates/new-york-city-taxi-fare-prediction/model/model_linear.py
----
📚 Documentation preview 📚: https://RDAgent--550.org.readthedocs.build/en/550/
=> fix: handle division by zero in percentage calculations

rdagent/log/ui/dsapp.py
----
📚 Documentation preview 📚: https://RDAgent--551.org.readthedocs.build/en/551/
=> fix: trace summary df showing in dsapp

rdagent/log/mle_summary.py, rdagent/log/ui/dsapp.py
----
📚 Documentation preview 📚: https://RDAgent--552.org.readthedocs.build/en/552/
=> fix: change summary info of log folder

rdagent/log/mle_summary.py
----
📚 Documentation preview 📚: https://RDAgent--554.org.readthedocs.build/en/554/
=> feat: exclude invalid session log folder

rdagent/log/ui/dsapp.py
----
📚 Documentation preview 📚: https://RDAgent--555.org.readthedocs.build/en/555/
=> feat: multi log folder, replace "epxx" in workspace path

rdagent/scenarios/data_science/debug/data.py
----
📚 Documentation preview 📚: https://RDAgent--557.org.readthedocs.build/en/557/
=> fix: keep some txt files

rdagent/scenarios/data_science/proposal/exp_gen.py, rdagent/utils/agent/workflow.py
…te_func
----
📚 Documentation preview 📚: https://RDAgent--558.org.readthedocs.build/en/558/
=> fix: fix task return dict with wrong format

rdagent/core/conf.py, rdagent/core/experiment.py, rdagent/log/storage.py, rdagent/utils/fmt.py
----
📚 Documentation preview 📚: https://RDAgent--559.org.readthedocs.build/en/559/
=> fix: add stdout context length setting and improve text shrinking logic

rdagent/log/mle_summary.py, rdagent/log/ui/dsapp.py
----
📚 Documentation preview 📚: https://RDAgent--560.org.readthedocs.build/en/560/
=> fix: summary stat number and dsapp bugs

rdagent/scenarios/data_science/scen/__init__.py
Add the shape of the CSV to the dataset description.
----
📚 Documentation preview 📚: https://RDAgent--561.org.readthedocs.build/en/561/
=> feat: add the shape of the CSV to the dataset description

rdagent/log/ui/dsapp.py
----
📚 Documentation preview 📚: https://RDAgent--563.org.readthedocs.build/en/563/
=> feat: add time info and stdout window in dsapp

rdagent/components/coder/data_science/ensemble/eval_tests/ensemble_test.txt, rdagent/components/coder/data_science/feature/eval_tests/feature_test.txt
----
📚 Documentation preview 📚: https://RDAgent--562.org.readthedocs.build/en/562/
=> chore: support multiple types in feature engineering

rdagent/scenarios/data_science/dev/feedback.py, rdagent/scenarios/data_science/dev/prompts.yaml, rdagent/scenarios/data_science/share.yaml
The format check result is not considered when proposing a new component.
----
📚 Documentation preview 📚: https://RDAgent--565.org.readthedocs.build/en/565/
=> chore: format check result

rdagent/components/coder/data_science/ensemble/eval_tests/ensemble_test.txt, rdagent/components/coder/data_science/workflow/eval.py
- add scores.csv check in ensemble_test.txt
- check scores.csv's content when fail to load scores.csv in workflow component
----
📚 Documentation preview 📚: https://RDAgent--567.org.readthedocs.build/en/567/
=> fix: add scores.csv checking in ensemble_test

rdagent/utils/env.py
----
📚 Documentation preview 📚: https://RDAgent--566.org.readthedocs.build/en/566/
=> fix: include data information in cache key generation

rdagent/core/proposal.py, rdagent/scenarios/data_science/proposal/exp_gen.py, rdagent/scenarios/data_science/proposal/prompts.yaml, rdagent/utils/repo/diff.py
----
📚 Documentation preview 📚: https://RDAgent--569.org.readthedocs.build/en/569/
=> feat: diff mode fix

rdagent/components/coder/data_science/ensemble/eval_tests/ensemble_test.txt, rdagent/components/coder/data_science/model/eval_tests/model_test.txt
----
📚 Documentation preview 📚: https://RDAgent--568.org.readthedocs.build/en/568/
=> fix: test end text change

rdagent/scenarios/data_science/dev/prompts.yaml
Refine the logic in feedback.
----
📚 Documentation preview 📚: https://RDAgent--571.org.readthedocs.build/en/571/
=> feat: refine the logic in feedback

rdagent/scenarios/data_science/dev/feedback.py, rdagent/utils/repo/diff.py
----
📚 Documentation preview 📚: https://RDAgent--574.org.readthedocs.build/en/574/
=> fix: use file dictionaries for diff generation in feedback module

rdagent/log/ui/dsapp.py
----
📚 Documentation preview 📚: https://RDAgent--575.org.readthedocs.build/en/575/
=> fix: score chart error catch

rdagent/components/coder/data_science/feature/eval_tests/feature_test.txt, rdagent/components/coder/data_science/raw_data_loader/eval_tests/data_loader_test.txt
Add the none check for data loader & feature output.
----
📚 Documentation preview 📚: https://RDAgent--577.org.readthedocs.build/en/577/
=> feat: add the none check for data loader & feature output

rdagent/scenarios/data_science/proposal/exp_gen.py, rdagent/scenarios/data_science/proposal/prompts.yaml
Refine the code in hypo&task generating.
----
📚 Documentation preview 📚: https://RDAgent--578.org.readthedocs.build/en/578/
=> fix: refine the code in hypo&task generating

rdagent/utils/__init__.py
----
📚 Documentation preview 📚: https://RDAgent--579.org.readthedocs.build/en/579/
=> fix: handle invalid regex patterns in filter_progress_bar function

rdagent/components/coder/data_science/model/__init__.py
----
📚 Documentation preview 📚: https://RDAgent--580.org.readthedocs.build/en/580/
=> fix: avoid length exception

rdagent/log/mle_summary.py, rdagent/log/ui/dsapp.py
----
📚 Documentation preview 📚: https://RDAgent--581.org.readthedocs.build/en/581/
=> feat: summary and UI update

rdagent/components/coder/data_science/ensemble/eval_tests/ensemble_test.txt
----
📚 Documentation preview 📚: https://RDAgent--586.org.readthedocs.build/en/586/
=> chore: ignore score value

rdagent/scenarios/data_science/scen/__init__.py
----
📚 Documentation preview 📚: https://RDAgent--588.org.readthedocs.build/en/588/
=> fix: sort file name for reproduction

rdagent/scenarios/data_science/debug/data.py
----
📚 Documentation preview 📚: https://RDAgent--589.org.readthedocs.build/en/589/
=> chore: sample group files by basename

rdagent/app/data_science/conf.py, rdagent/log/mle_summary.py, rdagent/log/ui/dsapp.py
----
📚 Documentation preview 📚: https://RDAgent--590.org.readthedocs.build/en/590/
=> feat: add baseline score stat

rdagent/log/mle_summary.py
Fix a bug in threshold score display.
----
📚 Documentation preview 📚: https://RDAgent--592.org.readthedocs.build/en/592/
=> fix: fix a bug in threshold score display

rdagent/scenarios/data_science/proposal/exp_gen.py
----
📚 Documentation preview 📚: https://RDAgent--593.org.readthedocs.build/en/593/
=> fix: ensure expected type

pyproject.toml, rdagent/app/data_science/loop.py, rdagent/components/coder/data_science/ensemble/eval.py, rdagent/components/coder/data_science/ensemble/exp.py, rdagent/components/coder/data_science/feature/eval.py, rdagent/components/coder/data_science/feature/exp.py, rdagent/components/coder/data_science/model/eval.py, rdagent/components/coder/data_science/model/exp.py, rdagent/components/coder/data_science/raw_data_loader/eval.py, rdagent/components/coder/data_science/raw_data_loader/exp.py, rdagent/components/coder/data_science/workflow/eval.py, rdagent/components/coder/data_science/workflow/exp.py, rdagent/oai/backend/deprec.py, rdagent/oai/llm_conf.py, rdagent/scenarios/data_science/dev/runner/__init__.py, rdagent/scenarios/data_science/dev/runner/eval.py, requirements.txt
----
📚 Documentation preview 📚: https://RDAgent--591.org.readthedocs.build/en/591/
=> feat: integrate azure deepseek r1

rdagent/components/coder/data_science/ensemble/eval_tests/ensemble_test.txt, rdagent/components/coder/data_science/ensemble/prompts.yaml, rdagent/components/coder/data_science/raw_data_loader/prompts.yaml, rdagent/scenarios/data_science/dev/prompts.yaml
Allow the LLM in the ensemble to focus on the significance of metrics.
Fix a bug in feedback.
----
📚 Documentation preview 📚: https://RDAgent--595.org.readthedocs.build/en/595/
=> fix: fix some bugs in the ensemble component

rdagent/core/experiment.py, rdagent/utils/env.py
----
📚 Documentation preview 📚: https://RDAgent--597.org.readthedocs.build/en/597/
=> fix: small bugs in cache rerun

rdagent/scenarios/data_science/proposal/exp_gen.py, rdagent/scenarios/data_science/proposal/prompts.yaml, rdagent/scenarios/kaggle/prompts.yaml
Fix a bug in proposal (add last loop's exception to last task desc).
----
📚 Documentation preview 📚: https://RDAgent--596.org.readthedocs.build/en/596/
=> fix: fix a bug in proposal (add last loop's exception to last task desc)

rdagent/oai/backend/deprec.py
----
📚 Documentation preview 📚: https://RDAgent--598.org.readthedocs.build/en/598/
=> fix: auto continue small bug

rdagent/scenarios/data_science/debug/data.py, rdagent/scenarios/data_science/scen/__init__.py
----
📚 Documentation preview 📚: https://RDAgent--600.org.readthedocs.build/en/600/
=> chore: print txt info

rdagent/components/coder/CoSTEER/__init__.py, rdagent/scenarios/data_science/dev/runner/__init__.py, rdagent/utils/env.py
----
📚 Documentation preview 📚: https://RDAgent--602.org.readthedocs.build/en/602/
=> fix: docker error will trigger retry and data science runner loop set to 3

rdagent/scenarios/data_science/debug/data.py, rdagent/scenarios/data_science/scen/__init__.py
----
📚 Documentation preview 📚: https://RDAgent--603.org.readthedocs.build/en/603/
=> chore: print head for txt files and shuffle when sample

rdagent/components/coder/data_science/model/prompts.yaml, rdagent/components/coder/data_science/raw_data_loader/prompts.yaml, rdagent/components/coder/data_science/workflow/prompts.yaml
Fix some minor bugs and add AutoML & cross-validation.
----
📚 Documentation preview 📚: https://RDAgent--604.org.readthedocs.build/en/604/
=> fix: fix some minor bugs and add AutoML & cross-validation

rdagent/components/coder/model_coder/eva_utils.py, rdagent/scenarios/kaggle/developer/feedback.py
----
📚 Documentation preview 📚: https://RDAgent--607.org.readthedocs.build/en/607/
=> refactor: replace Evaluator with CoSTEEREvaluator in eva_utils.py

rdagent/app/data_science/loop.py, rdagent/components/coder/data_science/raw_data_loader/exp.py
----
📚 Documentation preview 📚: https://RDAgent--609.org.readthedocs.build/en/609/
=> fix: restart small bug

rdagent/utils/env.py
when `python xx_test.py` is timeout, container can not get existing python outputs without "PYTHONUNBUFFERED"=1
----
📚 Documentation preview 📚: https://RDAgent--613.org.readthedocs.build/en/613/
=> fix: cannot get stdout when python test in container is timeout

rdagent/scenarios/data_science/dev/feedback.py, rdagent/scenarios/data_science/dev/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--608.org.readthedocs.build/en/608/
=> fix: sota comparison logic

rdagent/app/data_science/loop.py, rdagent/scenarios/data_science/experiment/experiment.py, rdagent/scenarios/data_science/proposal/exp_gen.py
----
📚 Documentation preview 📚: https://RDAgent--612.org.readthedocs.build/en/612/
=> fix: move next_component_required logic to DSTrace class and accurate implement

rdagent/components/coder/data_science/ensemble/eval_tests/ensemble_test.txt
Add a check for the name of ensemble's score in scores.csv.
----
📚 Documentation preview 📚: https://RDAgent--614.org.readthedocs.build/en/614/
=> fix: add a check for the name of ensemble's score in scores.csv

rdagent/utils/env.py
old timeout message will not be attached if docker run hit cache.
----
📚 Documentation preview 📚: https://RDAgent--620.org.readthedocs.build/en/620/
=> fix: move docker timeout message to __run()

rdagent/components/coder/data_science/feature/eval_tests/feature_test.txt, rdagent/components/coder/data_science/model/prompts.yaml, rdagent/scenarios/data_science/dev/runner/eval.py, rdagent/scenarios/data_science/proposal/exp_gen.py, rdagent/scenarios/data_science/proposal/prompts.yaml, rdagent/scenarios/data_science/share.yaml
----
📚 Documentation preview 📚: https://RDAgent--621.org.readthedocs.build/en/621/
=> fix: several bug fix including exp gen feature test and runner costeer

rdagent/components/coder/data_science/workflow/eval.py, rdagent/components/coder/data_science/workflow/eval_tests/submission_format_test.txt
Fix some bugs in workflow unit test.
----
📚 Documentation preview 📚: https://RDAgent--624.org.readthedocs.build/en/624/
=> fix: fix some bugs in workflow unit test

rdagent/components/coder/data_science/ensemble/prompts.yaml, rdagent/components/coder/data_science/feature/prompts.yaml, rdagent/components/coder/data_science/model/prompts.yaml, rdagent/components/coder/data_science/raw_data_loader/prompts.yaml, rdagent/components/coder/data_science/workflow/prompts.yaml
Fix a bug in cross validation.
----
📚 Documentation preview 📚: https://RDAgent--618.org.readthedocs.build/en/618/
=> fix: fix a bug in cross validation

rdagent/app/data_science/loop.py, rdagent/utils/workflow.py
The load function of LoopBase now accept a new parameter output_path to indicate the log and session output folder.
----
📚 Documentation preview 📚: https://RDAgent--628.org.readthedocs.build/en/628/
=> feat: add output_path to load function of LoopBase

rdagent/scenarios/data_science/proposal/exp_gen.py, rdagent/scenarios/data_science/proposal/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--630.org.readthedocs.build/en/630/
=> feat: refine component choosing part

rdagent/oai/backend/deprec.py, rdagent/oai/llm_conf.py
----
📚 Documentation preview 📚: https://RDAgent--632.org.readthedocs.build/en/632/
=> feat: make system prompt role customizable in LLM settings

rdagent/scenarios/data_science/proposal/exp_gen.py
Fix a bug in initial tasks.
----
📚 Documentation preview 📚: https://RDAgent--635.org.readthedocs.build/en/635/
=> fix: fix a bug in initial tasks

rdagent/components/coder/factor_coder/factor.py, rdagent/components/coder/model_coder/model.py, rdagent/core/exception.py, rdagent/core/experiment.py, rdagent/scenarios/qlib/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--636.org.readthedocs.build/en/636/
=> fix: qlib and other scenario bugs

rdagent/components/coder/data_science/feature/eval_tests/feature_test.txt
----
📚 Documentation preview 📚: https://RDAgent--638.org.readthedocs.build/en/638/
=> chore: ignore new numeric type

rdagent/components/coder/data_science/raw_data_loader/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--640.org.readthedocs.build/en/640/
=> fix: change ensemble metric calculation prompt's code tips

.gitignore, rdagent/core/experiment.py, rdagent/scenarios/data_science/proposal/exp_gen.py
Add inject_code_from_file_dict for FBWorkspace class.
----
📚 Documentation preview 📚: https://RDAgent--641.org.readthedocs.build/en/641/
=> fix: load code from file dict instead of folder

rdagent/scenarios/data_science/debug/data.py
----
📚 Documentation preview 📚: https://RDAgent--642.org.readthedocs.build/en/642/
=> chore: sample unique labels

rdagent/components/coder/data_science/raw_data_loader/prompts.yaml
Clarify cross validation.
----
📚 Documentation preview 📚: https://RDAgent--644.org.readthedocs.build/en/644/
=> fix: clarify cross validation

rdagent/components/coder/data_science/ensemble/__init__.py, rdagent/components/coder/data_science/ensemble/eval.py, rdagent/components/coder/data_science/ensemble/prompts.yaml, rdagent/components/coder/data_science/feature/__init__.py, rdagent/components/coder/data_science/feature/eval.py, rdagent/components/coder/data_science/feature/prompts.yaml, rdagent/components/coder/data_science/model/__init__.py, rdagent/components/coder/data_science/model/eval.py, rdagent/components/coder/data_science/model/prompts.yaml, rdagent/components/coder/data_science/raw_data_loader/__init__.py, rdagent/components/coder/data_science/raw_data_loader/eval.py, rdagent/components/coder/data_science/raw_data_loader/prompts.yaml, rdagent/components/coder/data_science/workflow/__init__.py, rdagent/components/coder/data_science/workflow/eval.py, rdagent/scenarios/data_science/dev/runner/eval.py, rdagent/scenarios/data_science/scen/__init__.py, rdagent/scenarios/data_science/scen/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--639.org.readthedocs.build/en/639/
=> feat: add eda to data science scenario

rdagent/components/coder/data_science/workflow/eval.py
----
📚 Documentation preview 📚: https://RDAgent--650.org.readthedocs.build/en/650/
=> fix: workflow eval logic

rdagent/scenarios/data_science/scen/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--651.org.readthedocs.build/en/651/
=> docs: add guidelines for competition participation in prompts.yaml

rdagent/components/coder/data_science/workflow/eval_tests/submission_format_test.txt
----
📚 Documentation preview 📚: https://RDAgent--653.org.readthedocs.build/en/653/
=> chore: scores.csv should not be rewritten

rdagent/app/data_science/loop.py, rdagent/utils/workflow.py
feat: add do_truncate control for the load function
----
📚 Documentation preview 📚: https://RDAgent--656.org.readthedocs.build/en/656/
=> feat: add do_truncate control for the load function

rdagent/components/coder/data_science/ensemble/eval_tests/ensemble_test.txt, rdagent/components/coder/data_science/ensemble/prompts.yaml, rdagent/components/coder/data_science/feature/eval_tests/feature_test.txt, rdagent/components/coder/data_science/model/eval_tests/model_test.txt, rdagent/components/coder/data_science/raw_data_loader/eval_tests/data_loader_test.txt
----
📚 Documentation preview 📚: https://RDAgent--658.org.readthedocs.build/en/658/
=> feat: variable printing tool of data_science coder testing

rdagent/scenarios/data_science/proposal/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--654.org.readthedocs.build/en/654/
=> fix: refine component selecting

rdagent/scenarios/data_science/proposal/exp_gen.py
----
📚 Documentation preview 📚: https://RDAgent--661.org.readthedocs.build/en/661/
=> fix: direct_exp_gen to json_target_type in DSExpGen class

rdagent/oai/backend/base.py
return single dimension if create_embedding receive a string input
----
📚 Documentation preview 📚: https://RDAgent--670.org.readthedocs.build/en/670/
=> fix: return 1D embedding if create_embedding receive a string input

rdagent/utils/env.py, test/utils/test_conf.py
----
📚 Documentation preview 📚: https://RDAgent--671.org.readthedocs.build/en/671/
=> fix: correct the configuration inheritance relationship

rdagent/log/mle_summary.py
----
📚 Documentation preview 📚: https://RDAgent--672.org.readthedocs.build/en/672/
=> feat: save mle_score to log folder with 'mle_score' tag

rdagent/utils/workflow.py
----
📚 Documentation preview 📚: https://RDAgent--673.org.readthedocs.build/en/673/
=> fix: change default to False of 'do_truncate'

rdagent/oai/backend/base.py, rdagent/oai/backend/deprec.py, rdagent/oai/backend/litellm.py
Display LLM prompt
----
📚 Documentation preview 📚: https://RDAgent--676.org.readthedocs.build/en/676/
=> feat: display LLM prompt

rdagent/utils/env.py
----
📚 Documentation preview 📚: https://RDAgent--677.org.readthedocs.build/en/677/
=> fix: timeout message adjustment for LocalEnv & DockerEnv

rdagent/components/knowledge_management/graph.py, rdagent/components/knowledge_management/vector_base.py
add constraint labels for semantic search
----
📚 Documentation preview 📚: https://RDAgent--680.org.readthedocs.build/en/680/
=> feat: add constraint labels for semantic search

rdagent/components/coder/data_science/ensemble/eval_tests/ensemble_test.txt, rdagent/components/coder/data_science/workflow/eval.py
----
📚 Documentation preview 📚: https://RDAgent--682.org.readthedocs.build/en/682/
=> fix: check 'ensemble' in scores.csv in workflow eval

rdagent/scenarios/data_science/dev/runner/eval.py
600s -> 3600s in running part
----
📚 Documentation preview 📚: https://RDAgent--683.org.readthedocs.build/en/683/
=> fix: running part timeout

rdagent/utils/agent/ret.py
----
📚 Documentation preview 📚: https://RDAgent--685.org.readthedocs.build/en/685/
=> fix: add default return value for python code extraction

README.md
----
📚 Documentation preview 📚: https://RDAgent--679.org.readthedocs.build/en/679/
=> docs: update README.md news

README.md
----
📚 Documentation preview 📚: https://RDAgent--689.org.readthedocs.build/en/689/
=> docs: update README.md video

rdagent/components/coder/data_science/model/prompts.yaml
Fix an error in `model_coder` prompt.
----
📚 Documentation preview 📚: https://RDAgent--690.org.readthedocs.build/en/690/
=> fix: fix an error in model_coder prompt

rdagent/components/coder/CoSTEER/evaluators.py, rdagent/components/coder/data_science/ensemble/eval.py, rdagent/components/coder/data_science/feature/eval.py, rdagent/components/coder/data_science/model/eval.py, rdagent/components/coder/data_science/raw_data_loader/eval.py, rdagent/components/coder/data_science/workflow/eval.py, rdagent/scenarios/data_science/dev/runner/eval.py
Sometimes, "final_decision" returned by LLM will be "true"/"false"(str❌)，not True/False(bool✅)，this will raise:
`TypeError: __bool__ should return bool, returned str`
So add one function to process this.
=> fix: validate and update 'final_decision' before init COSTEERFeedback

rdagent/components/coder/data_science/raw_data_loader/prompts.yaml, rdagent/components/coder/data_science/workflow/eval.py
Fix a bug related to model_name in ensemble.
----
📚 Documentation preview 📚: https://RDAgent--692.org.readthedocs.build/en/692/
=> fix: fix a bug related to model_name in ensemble

README.md
devault -> default
----
📚 Documentation preview 📚: https://RDAgent--688.org.readthedocs.build/en/688/
=> fix: change devault to default

rdagent/components/coder/data_science/raw_data_loader/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--694.org.readthedocs.build/en/694/
=> fix: fix a minor bug

rdagent/components/coder/data_science/workflow/eval.py, rdagent/scenarios/data_science/dev/runner/eval.py, rdagent/scenarios/data_science/dev/runner/eval_tests/mle_submission_format_test.txt
----
📚 Documentation preview 📚: https://RDAgent--693.org.readthedocs.build/en/693/
=> fix: runner COSTEER evaluator

rdagent/components/coder/data_science/raw_data_loader/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--695.org.readthedocs.build/en/695/
=> fix: preds_dict's keys

rdagent/components/coder/data_science/model/__init__.py
----
📚 Documentation preview 📚: https://RDAgent--699.org.readthedocs.build/en/699/
=> fix: add check when retrying gen model codes

rdagent/scenarios/data_science/proposal/prompts.yaml
Fix some description errors in direct_exp_gen.
----
📚 Documentation preview 📚: https://RDAgent--698.org.readthedocs.build/en/698/
=> fix: fix some description errors in direct_exp_gen

rdagent/scenarios/qlib/developer/factor_runner.py, rdagent/scenarios/qlib/docker/Dockerfile, rdagent/scenarios/qlib/experiment/factor_template/conf_combined.yaml, requirements.txt
----
📚 Documentation preview 📚: https://RDAgent--697.org.readthedocs.build/en/697/
=> fix: fix combined_factors_df.pkl not loading in docker

rdagent/scenarios/data_science/share.yaml
Align components' name.
----
📚 Documentation preview 📚: https://RDAgent--701.org.readthedocs.build/en/701/
=> fix: align components' name

rdagent/oai/backend/litellm.py, rdagent/oai/llm_conf.py
----
📚 Documentation preview 📚: https://RDAgent--702.org.readthedocs.build/en/702/
=> fix: default emb model

rdagent/utils/agent/tpl.yaml
Clarify an ambiguous explanation.
----
📚 Documentation preview 📚: https://RDAgent--705.org.readthedocs.build/en/705/
=> fix: clarify an ambiguous explanation

rdagent/components/coder/data_science/model/__init__.py
----
📚 Documentation preview 📚: https://RDAgent--707.org.readthedocs.build/en/707/
=> fix: change only model codes in model coder

.readthedocs.yaml, rdagent/scenarios/qlib/docker/Dockerfile
----
📚 Documentation preview 📚: https://RDAgent--709.org.readthedocs.build/en/709/
=> fix: fix docs build error

rdagent/components/coder/data_science/ensemble/eval_tests/ensemble_test.txt
Fix a bug in ensemble test script.
----
📚 Documentation preview 📚: https://RDAgent--713.org.readthedocs.build/en/713/
=> fix: fix a bug in ensemble test script

rdagent/app/data_science/loop.py
----
📚 Documentation preview 📚: https://RDAgent--714.org.readthedocs.build/en/714/
=> chore: add task type logger tag in coding

rdagent/core/conf.py, rdagent/core/experiment.py, rdagent/utils/fmt.py
----
📚 Documentation preview 📚: https://RDAgent--715.org.readthedocs.build/en/715/
=> feat: add line length limit to shrink_text function and settings

CONTRIBUTING.md, README.md
This pull request includes the following changes:
CONTRIBUTING.md:
Created a new file with guidelines for contributing to the RD-Agent project, including steps for getting started, how to contribute, code of conduct, reporting issues, and general guidelines.
Motivation and Context
These changes are required to:
Offer contributors a structured guide on how to contribute to the project, ensuring a smooth and efficient collaboration process.
----
📚 Documentation preview 📚: https://RDAgent--710.org.readthedocs.build/en/710/
=> docs: add contributing guidelines for rdagent

rdagent/log/ui/conf.py, rdagent/log/ui/dsapp.py
`dotenv run -- streamlit run rdagent/log/ui/dsapp.py`
----
📚 Documentation preview 📚: https://RDAgent--717.org.readthedocs.build/en/717/
=> chore: update data science scenario UI

README.md, docs/installation_and_configuration.rst
----
📚 Documentation preview 📚: https://RDAgent--721.org.readthedocs.build/en/721/
=> docs: add note on running docker without sudo in installation guides

rdagent/oai/backend/base.py, rdagent/oai/backend/litellm.py, rdagent/oai/llm_conf.py
----
📚 Documentation preview 📚: https://RDAgent--727.org.readthedocs.build/en/727/
=> feat: track and log accumulated completion cost in LiteLLMAPIBackend

rdagent/log/ui/dsapp.py
Add a tool to enable saving workspace files into a specific folder.
----
📚 Documentation preview 📚: https://RDAgent--728.org.readthedocs.build/en/728/
=> feat: add a tool to enable saving workspace files into a specific folder

rdagent/utils/__init__.py
Fix a bug in regular expression exception processing.
----
📚 Documentation preview 📚: https://RDAgent--734.org.readthedocs.build/en/734/
=> fix: fix a bug in regular expression exception processing

rdagent/app/data_science/conf.py, rdagent/components/coder/data_science/ensemble/__init__.py, rdagent/components/coder/data_science/raw_data_loader/prompts.yaml, rdagent/scenarios/data_science/proposal/prompts.yaml, rdagent/scenarios/data_science/scen/__init__.py, rdagent/scenarios/data_science/scen/prompts.yaml, rdagent/scenarios/data_science/share.yaml
----
📚 Documentation preview 📚: https://RDAgent--731.org.readthedocs.build/en/731/
=> feat: update prompts and descriptions for data science components

rdagent/app/data_science/conf.py, rdagent/components/coder/data_science/ensemble/__init__.py, rdagent/components/coder/data_science/ensemble/eval.py, rdagent/components/coder/data_science/feature/__init__.py, rdagent/components/coder/data_science/feature/eval.py, rdagent/components/coder/data_science/model/__init__.py, rdagent/components/coder/data_science/model/eval.py, rdagent/components/coder/data_science/raw_data_loader/__init__.py, rdagent/components/coder/data_science/raw_data_loader/eval.py, rdagent/components/coder/data_science/workflow/__init__.py, rdagent/scenarios/data_science/dev/runner/__init__.py
----
📚 Documentation preview 📚: https://RDAgent--737.org.readthedocs.build/en/737/
=> feat: costeer max loop as hyperp & skip workflow in eval

rdagent/scenarios/data_science/scen/__init__.py, rdagent/scenarios/data_science/scen/utils.py, requirements.txt
Add describe_data_folder_v2
----
📚 Documentation preview 📚: https://RDAgent--738.org.readthedocs.build/en/738/
=> feat: add describe_data_folder_v2

rdagent/app/qlib_rd_loop/factor_from_report.py, rdagent/components/workflow/rd_loop.py, rdagent/scenarios/qlib/docker/Dockerfile
----
📚 Documentation preview 📚: https://RDAgent--735.org.readthedocs.build/en/735/
=> fix: fix KeyError direct_exp_gen

rdagent/app/data_science/conf.py, rdagent/app/data_science/loop.py, rdagent/components/coder/data_science/pipeline/__init__.py, rdagent/components/coder/data_science/pipeline/eval.py, rdagent/components/coder/data_science/pipeline/eval_tests/submission_format_test.txt, rdagent/components/coder/data_science/pipeline/exp.py, rdagent/components/coder/data_science/pipeline/prompts.yaml, rdagent/oai/backend/base.py, rdagent/scenarios/data_science/dev/runner/eval.py, rdagent/scenarios/data_science/proposal/exp_gen/__init__.py, rdagent/scenarios/data_science/proposal/exp_gen/base.py, rdagent/scenarios/data_science/proposal/exp_gen/prompts.yaml, rdagent/scenarios/data_science/proposal/exp_gen/prompts_v2.yaml, rdagent/scenarios/data_science/proposal/exp_gen/proposal.py, rdagent/scenarios/data_science/scen/__init__.py, rdagent/scenarios/data_science/scen/prompts.yaml, rdagent/scenarios/data_science/share.yaml
----
📚 Documentation preview 📚: https://RDAgent--742.org.readthedocs.build/en/742/
=> feat: add pipeline coder

rdagent/scenarios/data_science/proposal/exp_gen/prompts_v2.yaml, rdagent/scenarios/data_science/proposal/exp_gen/proposal.py
----
📚 Documentation preview 📚: https://RDAgent--746.org.readthedocs.build/en/746/
=> feat: add hypothesis guidelines and rule-based ranking

rdagent/scenarios/data_science/proposal/exp_gen/prompts_v2.yaml, rdagent/scenarios/data_science/proposal/exp_gen/proposal.py
----
📚 Documentation preview 📚: https://RDAgent--750.org.readthedocs.build/en/750/
=> fix: a bug when score is a string

pyproject.toml, rdagent/scenarios/kaggle/experiment/kaggle_experiment.py, requirements.txt
----
📚 Documentation preview 📚: https://RDAgent--747.org.readthedocs.build/en/747/
=> fix: fix kaggle templates path error

rdagent/components/coder/data_science/workflow/eval.py
----
📚 Documentation preview 📚: https://RDAgent--748.org.readthedocs.build/en/748/
=> chore: entrypoint check

rdagent/scenarios/data_science/proposal/exp_gen/prompts_v2.yaml
----
📚 Documentation preview 📚: https://RDAgent--752.org.readthedocs.build/en/752/
=> fix: task_gen for better understanding

rdagent/components/coder/data_science/ensemble/eval_tests/ensemble_test.txt, rdagent/components/coder/data_science/pipeline/eval.py, rdagent/components/coder/data_science/workflow/eval.py
Add a check for whether values in score_df are NaN.
----
📚 Documentation preview 📚: https://RDAgent--756.org.readthedocs.build/en/756/
=> feat: add a check for whether values in score_df are NaN

rdagent/scenarios/data_science/share.yaml
----
📚 Documentation preview 📚: https://RDAgent--761.org.readthedocs.build/en/761/
=> fix: pretrained & validation alignment

rdagent/scenarios/data_science/proposal/exp_gen/proposal.py
----
📚 Documentation preview 📚: https://RDAgent--762.org.readthedocs.build/en/762/
=> fix: remove buggy info in hypothesis rank

rdagent/log/mle_summary.py, rdagent/log/ui/ds_summary.py, rdagent/log/ui/ds_trace.py, rdagent/utils/env.py
----
📚 Documentation preview 📚: https://RDAgent--757.org.readthedocs.build/en/757/
=> chore: data science scenario UI updates

rdagent/core/experiment.py
----
📚 Documentation preview 📚: https://RDAgent--755.org.readthedocs.build/en/755/
=> fix: set PYTHONPATH in env.run_ret_code call in FBWorkspace class

rdagent/components/coder/data_science/pipeline/eval.py, rdagent/log/ui/ds_trace.py, rdagent/scenarios/data_science/dev/runner/eval.py
----
📚 Documentation preview 📚: https://RDAgent--763.org.readthedocs.build/en/763/
=> fix: duplicate model names test in pipeline coder & runner

rdagent/scenarios/data_science/dev/feedback.py, rdagent/scenarios/data_science/dev/prompts.yaml
Add reviewer in feedback.
----
📚 Documentation preview 📚: https://RDAgent--765.org.readthedocs.build/en/765/
=> feat: add reviewer in feedback

rdagent/scenarios/data_science/proposal/exp_gen/naive.py, rdagent/scenarios/data_science/proposal/exp_gen/naive.yaml, rdagent/scenarios/data_science/proposal/exp_gen/prompts.yaml, rdagent/scenarios/data_science/proposal/exp_gen/prompts_v2.yaml, rdagent/scenarios/data_science/proposal/exp_gen/proposal.py, rdagent/scenarios/data_science/share.yaml
Merge failed and successful traces together.
----
📚 Documentation preview 📚: https://RDAgent--766.org.readthedocs.build/en/766/
=> feat: merge failed and successful traces together

rdagent/scenarios/data_science/dev/feedback.py
----
📚 Documentation preview 📚: https://RDAgent--771.org.readthedocs.build/en/771/
=> fix: small bug fix in feedback

rdagent/log/ui/ds_trace.py
----
📚 Documentation preview 📚: https://RDAgent--774.org.readthedocs.build/en/774/
=> chore: catch llm_data pkl read exception

rdagent/log/ui/ds_summary.py
----
📚 Documentation preview 📚: https://RDAgent--778.org.readthedocs.build/en/778/
=> chore: show sota exp valid score in summary page & combine curves

rdagent/utils/env.py, requirements.txt
----
📚 Documentation preview 📚: https://RDAgent--777.org.readthedocs.build/en/777/
=> feat: pull image with progress

rdagent/scenarios/data_science/dev/prompts.yaml, rdagent/scenarios/data_science/proposal/exp_gen/prompts_v2.yaml, rdagent/scenarios/data_science/proposal/exp_gen/proposal.py, rdagent/scenarios/data_science/share.yaml
----
📚 Documentation preview 📚: https://RDAgent--782.org.readthedocs.build/en/782/
=> refactor: refactor feedback logic and fix bug in task_gen

rdagent/scenarios/data_science/scen/__init__.py
Fix competition metric direction.
----
📚 Documentation preview 📚: https://RDAgent--784.org.readthedocs.build/en/784/
=> fix: fix competition metric direction

rdagent/scenarios/data_science/proposal/exp_gen/proposal.py
----
📚 Documentation preview 📚: https://RDAgent--783.org.readthedocs.build/en/783/
=> fix: add wait_retry to exp_gen v2

rdagent/app/data_science/loop.py, rdagent/scenarios/data_science/scen/__init__.py
----
📚 Documentation preview 📚: https://RDAgent--791.org.readthedocs.build/en/791/
=> fix: update metric direction to return bool

rdagent/oai/backend/base.py
----
📚 Documentation preview 📚: https://RDAgent--793.org.readthedocs.build/en/793/
=> feat: raise error when timeout in api call

rdagent/components/coder/data_science/ensemble/eval.py, rdagent/components/coder/data_science/feature/eval.py, rdagent/components/coder/data_science/model/eval.py, rdagent/components/coder/data_science/pipeline/eval.py, rdagent/components/coder/data_science/pipeline/eval_tests/submission_format_test.txt, rdagent/components/coder/data_science/pipeline/prompts.yaml, rdagent/components/coder/data_science/raw_data_loader/__init__.py, rdagent/components/coder/data_science/raw_data_loader/eval.py, rdagent/components/coder/data_science/raw_data_loader/prompts.yaml, rdagent/components/coder/data_science/share/eval.py, rdagent/components/coder/data_science/share/prompts.yaml, rdagent/components/coder/data_science/workflow/eval.py, rdagent/components/coder/data_science/workflow/eval_tests/submission_format_test.txt, rdagent/scenarios/data_science/dev/prompts.yaml, rdagent/scenarios/data_science/dev/runner/eval.py, rdagent/scenarios/data_science/proposal/exp_gen/naive.yaml, rdagent/scenarios/data_science/proposal/exp_gen/prompts.yaml, rdagent/scenarios/data_science/proposal/exp_gen/prompts_v2.yaml, rdagent/scenarios/data_science/scen/__init__.py, rdagent/scenarios/data_science/scen/prompts.yaml, rdagent/scenarios/data_science/share.yaml, rdagent/scenarios/kaggle/kaggle_crawler.py, rdagent/utils/agent/tpl.py, scenarios/data_science/share.yaml
----
📚 Documentation preview 📚: https://RDAgent--792.org.readthedocs.build/en/792/
=> refactor: use dynamic input path and update template loader

rdagent/scenarios/data_science/proposal/exp_gen/prompts_v2.yaml, rdagent/scenarios/data_science/proposal/exp_gen/proposal.py
----
📚 Documentation preview 📚: https://RDAgent--796.org.readthedocs.build/en/796/
=> fix: retry logic of hypothesis gen

rdagent/components/coder/data_science/ensemble/eval.py, rdagent/components/coder/data_science/feature/eval.py, rdagent/components/coder/data_science/model/eval.py, rdagent/components/coder/data_science/pipeline/eval.py, rdagent/components/coder/data_science/raw_data_loader/eval.py, rdagent/components/coder/data_science/workflow/eval.py, rdagent/scenarios/data_science/dev/feedback.py, rdagent/scenarios/data_science/dev/runner/eval.py
----
📚 Documentation preview 📚: https://RDAgent--800.org.readthedocs.build/en/800/
=> refactor: use remove_eda_part for EDA cleanup, fix diff eval

rdagent/app/data_science/conf.py, rdagent/app/data_science/loop.py, rdagent/log/timer.py, rdagent/oai/backend/base.py, rdagent/scenarios/data_science/proposal/exp_gen/proposal.py, rdagent/scenarios/data_science/share.yaml, rdagent/utils/workflow.py
----
📚 Documentation preview 📚: https://RDAgent--804.org.readthedocs.build/en/804/
=> feat: add pause resume to handle K8S cluster pause

rdagent/app/data_science/conf.py, rdagent/app/data_science/loop.py, rdagent/components/knowledge_management/graph.py, rdagent/components/knowledge_management/vector_base.py, rdagent/log/timer.py, rdagent/oai/backend/base.py, rdagent/oai/backend/litellm.py, rdagent/scenarios/data_science/dev/feedback.py, rdagent/scenarios/data_science/proposal/exp_gen/base.py, rdagent/scenarios/data_science/proposal/exp_gen/idea_pool.py, rdagent/scenarios/data_science/proposal/exp_gen/prompts_v2.yaml, rdagent/scenarios/data_science/proposal/exp_gen/proposal.py, rdagent/scenarios/data_science/share.yaml, rdagent/utils/agent/tpl.py, rdagent/utils/workflow.py
----
📚 Documentation preview 📚: https://RDAgent--795.org.readthedocs.build/en/795/
=> feat: idea pool integrated to exp_gen & add timer to RD-Agent & pause-resume to RD-loops

rdagent/scenarios/data_science/proposal/exp_gen/proposal.py
----
📚 Documentation preview 📚: https://RDAgent--806.org.readthedocs.build/en/806/
=> fix: bug in problem identification

rdagent/utils/workflow.py
----
📚 Documentation preview 📚: https://RDAgent--807.org.readthedocs.build/en/807/
=> fix: bug fix in timer start

rdagent/log/ui/ds_summary.py
----
📚 Documentation preview 📚: https://RDAgent--809.org.readthedocs.build/en/809/
=> feat: add select lite and select best button in summary page

rdagent/app/data_science/loop.py
----
📚 Documentation preview 📚: https://RDAgent--814.org.readthedocs.build/en/814/
=> feat: archive python and csv files in workspace to maintain results

rdagent/core/conf.py, rdagent/utils/workflow.py, requirements.txt
----
📚 Documentation preview 📚: https://RDAgent--815.org.readthedocs.build/en/815/
=> feat: add mlflow logger in RD loop to log

rdagent/app/data_science/conf.py
----
📚 Documentation preview 📚: https://RDAgent--820.org.readthedocs.build/en/820/
=> fix: update runner max loop to 1 in DS scenario

rdagent/components/coder/model_coder/evolving_strategy.py, rdagent/components/coder/model_coder/model_execute_template_v1.txt, rdagent/scenarios/qlib/experiment/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--821.org.readthedocs.build/en/821/
=> fix: fix model input shape bug and costeer_model bug

rdagent/oai/backend/litellm.py
----
📚 Documentation preview 📚: https://RDAgent--823.org.readthedocs.build/en/823/
=> fix: can set reasoning_effort=None in chat_model_map

rdagent/components/coder/model_coder/evolving_strategy.py, rdagent/components/coder/model_coder/model_execute_template_v1.txt, rdagent/scenarios/qlib/experiment/factor_template/read_exp_res.py, rdagent/scenarios/qlib/experiment/model_template/read_exp_res.py, rdagent/scenarios/qlib/experiment/prompts.yaml
Fix a bug in docker result extraction
----
📚 Documentation preview 📚: https://RDAgent--824.org.readthedocs.build/en/824/
=> fix: fix a bug in docker result extraction

rdagent/oai/backend/base.py, rdagent/utils/workflow.py
----
📚 Documentation preview 📚: https://RDAgent--826.org.readthedocs.build/en/826/
=> fix: add time to timer when api timeout bug

rdagent/scenarios/data_science/dev/prompts.yaml, rdagent/scenarios/data_science/proposal/exp_gen/prompts_v2.yaml, rdagent/scenarios/data_science/share.yaml
----
📚 Documentation preview 📚: https://RDAgent--827.org.readthedocs.build/en/827/
=> feat: propose hypothesis across multiple parts in pipeline

rdagent/scenarios/data_science/proposal/exp_gen/prompts_v2.yaml, rdagent/scenarios/data_science/proposal/exp_gen/proposal.py
----
📚 Documentation preview 📚: https://RDAgent--828.org.readthedocs.build/en/828/
=> fix: add pipeline to hypothesis spec

rdagent/oai/backend/litellm.py
----
📚 Documentation preview 📚: https://RDAgent--829.org.readthedocs.build/en/829/
=> chore: log cost object

rdagent/app/data_science/loop.py
…e kb from json file
----
📚 Documentation preview 📚: https://RDAgent--835.org.readthedocs.build/en/835/
=> fix: bug when restart with kb and different pkl path, initialize the kb from json file

rdagent/scenarios/data_science/proposal/exp_gen/draft.py, rdagent/scenarios/data_science/proposal/exp_gen/prompts_drafting.yaml
----
📚 Documentation preview 📚: https://RDAgent--840.org.readthedocs.build/en/840/
=> fix: new draft bugs

rdagent/log/ui/ds_summary.py, rdagent/log/ui/ds_trace.py, rdagent/scenarios/data_science/proposal/exp_gen/base.py, rdagent/scenarios/data_science/proposal/exp_gen/merge.py, rdagent/scenarios/data_science/proposal/exp_gen/merge.yaml
----
📚 Documentation preview 📚: https://RDAgent--841.org.readthedocs.build/en/841/
=> fix: adapting UI to mock trace

rdagent/scenarios/data_science/proposal/exp_gen/merge.py, rdagent/scenarios/data_science/share.yaml
----
📚 Documentation preview 📚: https://RDAgent--842.org.readthedocs.build/en/842/
=> feat: refine merge

rdagent/log/ui/ds_summary.py, rdagent/log/ui/ds_trace.py, rdagent/log/ui/dsapp.py
----
📚 Documentation preview 📚: https://RDAgent--844.org.readthedocs.build/en/844/
=> chore: ui change

rdagent/log/ui/ds_trace.py
----
📚 Documentation preview 📚: https://RDAgent--845.org.readthedocs.build/en/845/
=> chore: fix get loop id bug in ui

rdagent/scenarios/data_science/test_eval.py
----
📚 Documentation preview 📚: https://RDAgent--846.org.readthedocs.build/en/846/
=> fix: wrong variable test_eval.py

rdagent/scenarios/data_science/test_eval.py
----
📚 Documentation preview 📚: https://RDAgent--847.org.readthedocs.build/en/847/
=> fix: non-exist variable test_eval.py

rdagent/app/data_science/conf.py, rdagent/app/data_science/loop.py, rdagent/scenarios/data_science/proposal/exp_gen/merge.py, rdagent/scenarios/data_science/proposal/exp_gen/sota_exp_select.py
----
📚 Documentation preview 📚: https://RDAgent--843.org.readthedocs.build/en/843/
=> feat: multi trace merge

rdagent/components/coder/data_science/share/eval.py, rdagent/components/coder/data_science/share/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--850.org.readthedocs.build/en/850/
=> chore: dump test data

rdagent/log/ui/ds_trace.py, rdagent/scenarios/data_science/proposal/exp_gen/merge.py, rdagent/scenarios/data_science/test_eval.py
----
📚 Documentation preview 📚: https://RDAgent--853.org.readthedocs.build/en/853/
=> fix: adjust ds_trace lookup and add stderr redirect to mlebench command

rdagent/log/mle_summary.py, rdagent/log/ui/ds_summary.py, rdagent/log/ui/dsapp.py
----
📚 Documentation preview 📚: https://RDAgent--854.org.readthedocs.build/en/854/
=> chore: add cache for UI summary, remove workspace dependency when generate summary

rdagent/app/data_science/loop.py, rdagent/oai/backend/base.py, rdagent/oai/backend/litellm.py, rdagent/scenarios/data_science/proposal/exp_gen/prompts_v2.yaml
----
📚 Documentation preview 📚: https://RDAgent--856.org.readthedocs.build/en/856/
=> fix: refine the time/memory constraints prompt in hypothesis proposal

rdagent/log/mle_summary.py
Use LoopBase.loop_trace now, more accurate
----
📚 Documentation preview 📚: https://RDAgent--858.org.readthedocs.build/en/858/
=> fix: change method of cut log trace

rdagent/oai/backend/base.py, rdagent/oai/llm_conf.py
----
📚 Documentation preview 📚: https://RDAgent--859.org.readthedocs.build/en/859/
=> fix: make timeout fail a hyper parameter

rdagent/log/timer.py, rdagent/oai/backend/base.py, rdagent/utils/workflow.py
----
📚 Documentation preview 📚: https://RDAgent--860.org.readthedocs.build/en/860/
=> feat: log api status to mlflow

rdagent/utils/workflow.py
----
📚 Documentation preview 📚: https://RDAgent--861.org.readthedocs.build/en/861/
=> fix: typo in workflow

rdagent/app/data_science/conf.py, rdagent/components/coder/data_science/share/eval.py, rdagent/scenarios/data_science/scen/__init__.py, rdagent/scenarios/data_science/scen/utils.py
----
📚 Documentation preview 📚: https://RDAgent--864.org.readthedocs.build/en/864/
=> chore: custom data refine

README.md
----
📚 Documentation preview 📚: https://RDAgent--870.org.readthedocs.build/en/870/
=> chore: news MLE-bench release

rdagent/log/logger.py, rdagent/log/ui/ds_summary.py, rdagent/log/ui/ds_trace.py
----
📚 Documentation preview 📚: https://RDAgent--874.org.readthedocs.build/en/874/
=> chore: logger storage and ui changes

README.md
----
📚 Documentation preview 📚: https://RDAgent--876.org.readthedocs.build/en/876/
=> docs: fix a small typo in README

rdagent/scenarios/data_science/proposal/exp_gen/idea_pool.py, rdagent/scenarios/data_science/scen/utils.py
----
📚 Documentation preview 📚: https://RDAgent--877.org.readthedocs.build/en/877/
=> fix: improve file tree and _walk symlink handling

rdagent/components/coder/data_science/share/eval.py
----
📚 Documentation preview 📚: https://RDAgent--878.org.readthedocs.build/en/878/
=> fix: update DS env setup with competition volume and timeout

rdagent/components/coder/data_science/share/eval.py
----
📚 Documentation preview 📚: https://RDAgent--882.org.readthedocs.build/en/882/
=> fix: use fallback messages for missing submission and scores files

rdagent/log/base.py, rdagent/log/storage.py
1. only return .pkl file in trace log storage (by default).
2. can provide "tag=xxx" to filter pkl file in log storage.
example code
```python
loop1_coding_msgs = [i for i in FileStorage(trace_path).iter_msg(tag="Loop_1.coding")]
```
----
📚 Documentation preview 📚: https://RDAgent--883.org.readthedocs.build/en/883/
=> chore: log storage refine

.github/workflows/ci.yml, rdagent/log/ui/ds_summary.py
----
📚 Documentation preview 📚: https://RDAgent--884.org.readthedocs.build/en/884/
=> chore: ui bug fix

.github/workflows/ci.yml
----
📚 Documentation preview 📚: https://RDAgent--885.org.readthedocs.build/en/885/
=> fix: fix mypy check dependence error

README.md
----
📚 Documentation preview 📚: https://RDAgent--893.org.readthedocs.build/en/893/
=> docs: update paper report

rdagent/app/data_science/conf.py, rdagent/log/mle_summary.py, rdagent/scenarios/data_science/proposal/exp_gen/base.py, rdagent/scenarios/data_science/proposal/exp_gen/idea_pool.py, rdagent/scenarios/data_science/proposal/exp_gen/merge.py, rdagent/scenarios/data_science/proposal/exp_gen/proposal.py, rdagent/scenarios/data_science/proposal/exp_gen/sota_exp_select.py
- add MAX_SOTA_NUM  constrains in DStrace.experiment_and_feedback_list_after_init(), which will be used in AutoSotaSelector
- fix a small logic bug in DSProposalV2ExpGen
- finish debug-test on GCR
----
📚 Documentation preview 📚: https://RDAgent--892.org.readthedocs.build/en/892/
=> fix: fix the bug of Exceed-LLM-Context in online merge of multi-tarce

rdagent/oai/backend/base.py, rdagent/oai/llm_conf.py
----
📚 Documentation preview 📚: https://RDAgent--894.org.readthedocs.build/en/894/
=> feat: raise policy violation

rdagent/utils/__init__.py, rdagent/utils/fmt.py
----
📚 Documentation preview 📚: https://RDAgent--890.org.readthedocs.build/en/890/
=> fix: fix the bug in the regular expression matching for stdout

rdagent/log/ui/utils.py
----
📚 Documentation preview 📚: https://RDAgent--897.org.readthedocs.build/en/897/
=> chore: add select_best param for log.ui.utils.compare tool function

README.md, docs/scens/catalog.rst, docs/scens/data_science.rst
----
📚 Documentation preview 📚: https://RDAgent--896.org.readthedocs.build/en/896/
=> docs: update guidance for running mle-bench

rdagent/utils/env.py
----
📚 Documentation preview 📚: https://RDAgent--899.org.readthedocs.build/en/899/
=> chore: add kill after for timeout

rdagent/scenarios/data_science/dev/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--901.org.readthedocs.build/en/901/
=> fix: refine feedback prompt

rdagent/log/mle_summary.py
----
📚 Documentation preview 📚: https://RDAgent--911.org.readthedocs.build/en/911/
=> fix: loop_num count logic when summarize trace

rdagent/scenarios/data_science/proposal/exp_gen/ckp_select.py
----
📚 Documentation preview 📚: https://RDAgent--909.org.readthedocs.build/en/909/
=> fix: use trace count as index

rdagent/oai/backend/deprec.py, rdagent/oai/backend/litellm.py, rdagent/utils/env.py
----
📚 Documentation preview 📚: https://RDAgent--912.org.readthedocs.build/en/912/
=> fix: default cost to NaN when calculation fails in LiteLLM backend

README.md
Update README for RD-Agent(Q).
----
📚 Documentation preview 📚: https://RDAgent--913.org.readthedocs.build/en/913/
=> docs: update README for RD-Agent(Q)

rdagent/log/ui/ds_trace.py, rdagent/utils/workflow.py
----
📚 Documentation preview 📚: https://RDAgent--929.org.readthedocs.build/en/929/
=> fix: ds trace

rdagent/log/ui/ds_trace.py
----
📚 Documentation preview 📚: https://RDAgent--934.org.readthedocs.build/en/934/
=> chore: ui update

rdagent/log/ui/app.py
----
📚 Documentation preview 📚: https://RDAgent--935.org.readthedocs.build/en/935/
=> fix: detect scenario logic

rdagent/components/coder/factor_coder/prompts.yaml, rdagent/scenarios/qlib/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--928.org.readthedocs.build/en/928/
=> feat: update prompt to improve json respond format of some LLM models

rdagent/utils/env.py
----
📚 Documentation preview 📚: https://RDAgent--945.org.readthedocs.build/en/945/
=> chore: continue to read output

rdagent/scenarios/data_science/proposal/exp_gen/base.py, rdagent/scenarios/data_science/scen/utils.py
* Added filtering for system-generated directories/files in the file_tree function
* Updated the DSTrace class by introducing the current_selection attribute to prevent access errors
The issue https://github.com/microsoft/RD-Agent/issues/925
Running `rdagent kaggle --competition mlsp-2013-birds --step-n=3`, the original code exits due to the inability to read the binary files.
The modified program automatically skips system-generated metadata directories and runs correctly.
----
📚 Documentation preview 📚: https://RDAgent--946.org.readthedocs.build/en/946/
=> fix: filter system metadata dirs and init missing DSTrace attribute

rdagent/scenarios/qlib/experiment/utils.py
----
📚 Documentation preview 📚: https://RDAgent--954.org.readthedocs.build/en/954/
=> chore: print out the qlib data generation error message to help user find the problem

rdagent/utils/env.py
----
📚 Documentation preview 📚: https://RDAgent--955.org.readthedocs.build/en/955/
=> fix: add missing semicolon after chmod in env shell command

rdagent/app/data_science/conf.py, rdagent/components/coder/model_coder/evolving_strategy.py, rdagent/scenarios/data_science/example/arf-12-hour-prediction-task/description.md, rdagent/scenarios/data_science/example/arf-12-hour-prediction-task/sample.py, rdagent/scenarios/data_science/example/eval/arf-12-hour-prediction-task/grade.py, rdagent/scenarios/data_science/example/eval/arf-12-hour-prediction-task/valid.py, rdagent/scenarios/data_science/proposal/exp_gen/idea_pool.py, rdagent/scenarios/data_science/scen/__init__.py, rdagent/scenarios/qlib/developer/feedback.py, requirements.txt, test/utils/test_import.py
Add custom data setting for data science scene.
----
📚 Documentation preview 📚: https://RDAgent--967.org.readthedocs.build/en/967/
=> refactor: add custom data setting for data science scene

rdagent/scenarios/kaggle/kaggle_crawler.py
----
📚 Documentation preview 📚: https://RDAgent--970.org.readthedocs.build/en/970/
=> fix: get_metric_direction for aerial-cactus-identification

docs/scens/data_science.rst
Update the documentation for custom dataset.
----
📚 Documentation preview 📚: https://RDAgent--969.org.readthedocs.build/en/969/
=> docs: update the documentation for custom dataset

rdagent/components/coder/data_science/conf.py, rdagent/utils/env.py
----
📚 Documentation preview 📚: https://RDAgent--966.org.readthedocs.build/en/966/
=> fix: use simple stdout and stderr

README.md, docs/scens/data_science.rst
----
📚 Documentation preview 📚: https://RDAgent--973.org.readthedocs.build/en/973/
=> docs: update readme for v0.5.0 release

docs/scens/data_science.rst, rdagent/log/mle_summary.py
----
📚 Documentation preview 📚: https://RDAgent--978.org.readthedocs.build/en/978/
=> fix: fix a bug and update the docs

rdagent/log/ui/ds_trace.py
----
📚 Documentation preview 📚: https://RDAgent--985.org.readthedocs.build/en/985/
=> fix: ui llm log bug

rdagent/scenarios/kaggle/kaggle_crawler.py, rdagent/utils/workflow/loop.py
----
📚 Documentation preview 📚: https://RDAgent--986.org.readthedocs.build/en/986/
=> fix: support tar in dataset & fix a small bug in loop

rdagent/scenarios/data_science/proposal/exp_gen/base.py, rdagent/scenarios/data_science/proposal/exp_gen/prompts_v2.yaml, rdagent/scenarios/data_science/proposal/exp_gen/prompts_v3.yaml, rdagent/scenarios/data_science/proposal/exp_gen/proposal.py
----
📚 Documentation preview 📚: https://RDAgent--987.org.readthedocs.build/en/987/
=> fix: refine prompt

rdagent/log/ui/ds_trace.py
----
📚 Documentation preview 📚: https://RDAgent--993.org.readthedocs.build/en/993/
=> fix: improve log folder sorting and selection UX

rdagent/core/proposal.py, rdagent/log/utils/__init__.py, rdagent/oai/backend/base.py, rdagent/scenarios/data_science/dev/feedback.py, rdagent/scenarios/data_science/dev/prompts.yaml, rdagent/scenarios/data_science/share.yaml
----
📚 Documentation preview 📚: https://RDAgent--1000.org.readthedocs.build/en/1000/
=> feat: add code change summary

rdagent/components/coder/data_science/pipeline/prompts.yaml, rdagent/components/coder/data_science/raw_data_loader/prompts.yaml, rdagent/scenarios/data_science/scen/utils.py
----
📚 Documentation preview 📚: https://RDAgent--1004.org.readthedocs.build/en/1004/
=> feat: add hide_base_name option and update data folder prompts

.devcontainer/Dockerfile, .devcontainer/README.md, .devcontainer/devcontainer.json, .devcontainer/env
----
📚 Documentation preview 📚: https://RDAgent--997.org.readthedocs.build/en/997/
=> chore: add devcontainer Dockerfile, devcontainer.json, and env

rdagent/components/coder/data_science/ensemble/eval.py, rdagent/components/coder/data_science/feature/eval.py, rdagent/components/coder/data_science/model/eval.py, rdagent/components/coder/data_science/pipeline/eval.py, rdagent/components/coder/data_science/raw_data_loader/eval.py, rdagent/components/coder/data_science/workflow/eval.py, rdagent/scenarios/data_science/dev/runner/eval.py, rdagent/scenarios/data_science/test_eval.py
----
📚 Documentation preview 📚: https://RDAgent--1012.org.readthedocs.build/en/1012/
=> fix: fix a minor bug in DS eval

rdagent/scenarios/data_science/proposal/exp_gen/README.md
----
📚 Documentation preview 📚: https://RDAgent--1010.org.readthedocs.build/en/1010/
=> docs: add README for exp_gen folder structure proposal

rdagent/components/workflow/rd_loop.py, rdagent/log/ui/ds_trace.py, rdagent/oai/backend/litellm.py, rdagent/scenarios/data_science/loop.py
- save SETTINGS to trace folder
- show first evo round codes diff
----
📚 Documentation preview 📚: https://RDAgent--1009.org.readthedocs.build/en/1009/
=> feat: show first evo round codes diff

rdagent/oai/backend/base.py, requirements.txt
----
📚 Documentation preview 📚: https://RDAgent--1019.org.readthedocs.build/en/1019/
=> chore: document APIBackend parameters and remove sparse dep

rdagent/app/data_science/loop.py, rdagent/log/server/app.py
----
📚 Documentation preview 📚: https://RDAgent--1022.org.readthedocs.build/en/1022/
=> chore: restore parameter timeout in loop

README.md, docs/installation_and_configuration.rst, rdagent/components/coder/factor_coder/evolving_strategy.py, rdagent/oai/backend/base.py, rdagent/scenarios/qlib/prompts.yaml
When running qlib, fix the following issues based on error messages:
1. When generating hypothesis doesn't return a string, add supplementary prompt
2. DeepSeek's JSON format errors: 
a. Returns True/False, fix Python-style boolean values to JSON standard format
b. Output code uses ```python xxx``` format, add similar parsing logic
c. Returns multiple blocks, like ```json xxx``` ```python```, parse the first one by default
3. Provide DeepSeek's example configuration, only need to provide DeepSeek and SiliconFlow's API keys
----
📚 Documentation preview 📚: https://RDAgent--1024.org.readthedocs.build/en/1024/
=> fix: support experimental support for Deepseek models and update docs about configuration

rdagent/core/proposal.py, rdagent/log/ui/app.py, rdagent/scenarios/qlib/experiment/workspace.py
----
📚 Documentation preview 📚: https://RDAgent--1026.org.readthedocs.build/en/1026/
=> fix: fix some bugs in quant scen

requirements.txt
----
📚 Documentation preview 📚: https://RDAgent--1029.org.readthedocs.build/en/1029/
=> chore: add dependence

rdagent/scenarios/data_science/proposal/exp_gen/proposal.py
----
📚 Documentation preview 📚: https://RDAgent--1037.org.readthedocs.build/en/1037/
=> fix: properly assign sota_exp_fb before None comparison

rdagent/oai/backend/base.py, rdagent/oai/backend/litellm.py
----
📚 Documentation preview 📚: https://RDAgent--1043.org.readthedocs.build/en/1043/
=> fix: fix a small bug in response_schema

rdagent/log/server/app.py
----
📚 Documentation preview 📚: https://RDAgent--1050.org.readthedocs.build/en/1050/
=> fix: path traversal risk

.devcontainer/README.md, .devcontainer/devcontainer.json
----
📚 Documentation preview 📚: https://RDAgent--1054.org.readthedocs.build/en/1054/
=> docs: add submission grading steps to devcontainer README

README.md
----
📚 Documentation preview 📚: https://RDAgent--1058.org.readthedocs.build/en/1058/
=> docs: update installation methods in readme

docs/installation_and_configuration.rst
----
📚 Documentation preview 📚: https://RDAgent--1060.org.readthedocs.build/en/1060/
=> docs: add Properties code-block for BACKEND setting in docs

rdagent/components/coder/data_science/pipeline/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--1065.org.readthedocs.build/en/1065/
=> fix: error in prompt template

rdagent/app/utils/ws.py, rdagent/components/coder/data_science/conf.py, rdagent/utils/env.py, test/utils/test_conf.py
----
📚 Documentation preview 📚: https://RDAgent--1066.org.readthedocs.build/en/1066/
=> feat: add ws CLI and support optional timeout/cache

rdagent/log/ui/app.py
----
📚 Documentation preview 📚: https://RDAgent--1073.org.readthedocs.build/en/1073/
=> fix: filter log folders bug in ui

rdagent/oai/backend/litellm.py
----
📚 Documentation preview 📚: https://RDAgent--1074.org.readthedocs.build/en/1074/
=> chore: log LITELLM_SETTINGS when first use

rdagent/scenarios/data_science/dev/runner/__init__.py, rdagent/scenarios/data_science/dev/runner/prompts.yaml, rdagent/scenarios/data_science/proposal/exp_gen/prompts_v2.yaml, rdagent/scenarios/data_science/scen/prompts.yaml, rdagent/scenarios/data_science/share.yaml
----
📚 Documentation preview 📚: https://RDAgent--1076.org.readthedocs.build/en/1076/
=> fix: refine prompt; runner focus on low hanging fruit

rdagent/components/coder/data_science/pipeline/__init__.py, rdagent/components/coder/data_science/raw_data_loader/__init__.py, rdagent/scenarios/data_science/dev/runner/eval.py, rdagent/scenarios/data_science/proposal/exp_gen/draft/draft.py, rdagent/scenarios/data_science/scen/runtime_info.py
----
📚 Documentation preview 📚: https://RDAgent--1089.org.readthedocs.build/en/1089/
=> fix: minor fix to runtime_environment

rdagent/log/ui/ds_trace.py
----
📚 Documentation preview 📚: https://RDAgent--1090.org.readthedocs.build/en/1090/
=> fix: llm chatbot text_area key bug

rdagent/scenarios/data_science/proposal/exp_gen/proposal.py
old code will set component="HypothesisComponent.Ensemble" in Hypothesis Class,
new code will set component="Ensemble" in Hypothesis Class.
----
📚 Documentation preview 📚: https://RDAgent--1091.org.readthedocs.build/en/1091/
=> fix: use enum value when generate hypothesis

rdagent/scenarios/data_science/dev/runner/__init__.py, test/utils/test_conf.py
----
📚 Documentation preview 📚: https://RDAgent--1096.org.readthedocs.build/en/1096/
=> fix: use CoSTEERSettings for DSRunnerCoSTEERSettings

rdagent/components/coder/data_science/conf.py, rdagent/components/coder/data_science/pipeline/__init__.py, rdagent/oai/backend/base.py, rdagent/oai/backend/deprec.py, rdagent/oai/backend/litellm.py, requirements.txt
----
📚 Documentation preview 📚: https://RDAgent--1097.org.readthedocs.build/en/1097/
=> feat: add extra_eval config and import_class for custom evaluators

rdagent/log/ui/ds_trace.py
----
📚 Documentation preview 📚: https://RDAgent--1099.org.readthedocs.build/en/1099/
=> chore: add response format in chatbot

rdagent/log/ui/utils.py
----
📚 Documentation preview 📚: https://RDAgent--1102.org.readthedocs.build/en/1102/
=> chore: update figure

rdagent/log/ui/ds_trace.py, rdagent/log/ui/utils.py
----
📚 Documentation preview 📚: https://RDAgent--1105.org.readthedocs.build/en/1105/
=> chore: show merge loop in figure

rdagent/app/data_science/conf.py, rdagent/components/proposal/__init__.py, rdagent/core/experiment.py, rdagent/core/proposal.py, rdagent/scenarios/data_science/proposal/exp_gen/draft/draft.py, rdagent/scenarios/data_science/proposal/exp_gen/merge.py, rdagent/scenarios/data_science/proposal/exp_gen/naive.py, rdagent/scenarios/data_science/proposal/exp_gen/parallel.py, rdagent/scenarios/data_science/proposal/exp_gen/planner/__init__.py, rdagent/scenarios/data_science/proposal/exp_gen/prompts_v2.yaml, rdagent/scenarios/data_science/proposal/exp_gen/proposal.py, rdagent/scenarios/data_science/proposal/exp_gen/router/__init__.py, rdagent/scenarios/data_science/share.yaml
----
📚 Documentation preview 📚: https://RDAgent--1103.org.readthedocs.build/en/1103/
=> feat: enable meta planner

rdagent/app/utils/health_check.py
----
📚 Documentation preview 📚: https://RDAgent--1111.org.readthedocs.build/en/1111/
=> fix: health check bug

rdagent/app/cli.py, rdagent/app/qlib_rd_loop/factor_from_report.py, rdagent/app/qlib_rd_loop/model.py, rdagent/app/qlib_rd_loop/quant.py
----
📚 Documentation preview 📚: https://RDAgent--1114.org.readthedocs.build/en/1114/
=> fix: cli command type checker

rdagent/scenarios/data_science/dev/feedback.py, rdagent/scenarios/data_science/dev/prompts.yaml, rdagent/scenarios/data_science/loop.py, rdagent/scenarios/data_science/proposal/exp_gen/base.py, rdagent/scenarios/data_science/share.yaml, rdagent/utils/workflow/loop.py
----
📚 Documentation preview 📚: https://RDAgent--1116.org.readthedocs.build/en/1116/
=> feat: analyze feedback based on sota numbers

rdagent/log/ui/ds_trace.py
----
📚 Documentation preview 📚: https://RDAgent--1118.org.readthedocs.build/en/1118/
=> fix: curve bug

rdagent/log/ui/ds_summary.py, rdagent/log/ui/utils.py
----
📚 Documentation preview 📚: https://RDAgent--1119.org.readthedocs.build/en/1119/
=> feat: add lite curves figure

rdagent/scenarios/data_science/dev/feedback.py
----
📚 Documentation preview 📚: https://RDAgent--1120.org.readthedocs.build/en/1120/
=> fix: fix a small bug in feedback

rdagent/log/ui/utils.py
----
📚 Documentation preview 📚: https://RDAgent--1121.org.readthedocs.build/en/1121/
=> fix: sota_exp is None when get_sota_exp_stat

rdagent/scenarios/data_science/dev/runner/__init__.py, rdagent/utils/agent/apply_patch.py, rdagent/utils/agent/ret.py
The code diff mode for runner can be enabled by `DS_RUNNER_COSTEER_DIFF_MODE=True`
=> fix: fix code diff bug

rdagent/log/ui/ds_trace.py
----
📚 Documentation preview 📚: https://RDAgent--1124.org.readthedocs.build/en/1124/
=> fix: last SOTA diff in ui

rdagent/core/experiment.py
----
📚 Documentation preview 📚: https://RDAgent--1140.org.readthedocs.build/en/1140/
=> fix: ignore RuntimeError for shared workspace double recovery

rdagent/app/qlib_rd_loop/factor_from_report.py, rdagent/scenarios/qlib/developer/factor_runner.py, rdagent/scenarios/qlib/developer/model_runner.py, rdagent/scenarios/qlib/proposal/quant_proposal.py
Fix some bugs in RD-Agent(Q)
----
📚 Documentation preview 📚: https://RDAgent--1143.org.readthedocs.build/en/1143/
=> fix: fix some bugs in RD-Agent(Q)

rdagent/log/mle_summary.py, rdagent/log/ui/utils.py
----
📚 Documentation preview 📚: https://RDAgent--1146.org.readthedocs.build/en/1146/
=> chore: overwrite sota exp stat in summary page

rdagent/scenarios/data_science/dev/runner/__init__.py
----
📚 Documentation preview 📚: https://RDAgent--1148.org.readthedocs.build/en/1148/
=> fix: fix the runner bug when deciding debug or refine

rdagent/log/ui/ds_trace.py, rdagent/oai/backend/base.py, rdagent/scenarios/data_science/proposal/exp_gen/router/__init__.py, rdagent/utils/workflow/loop.py
----
📚 Documentation preview 📚: https://RDAgent--1151.org.readthedocs.build/en/1151/
=> feat: save more time info, exp_gen, llm start-end

README.md, docs/installation_and_configuration.rst, rdagent/scenarios/data_science/example/arf-12-hours-prediction-task/sample.py, rdagent/scenarios/data_science/example/eval/arf-12-hours-prediction-task/grade.py, rdagent/scenarios/data_science/example/source_data/arf-12-hours-prediction-task/prepare.py
----
📚 Documentation preview 📚: https://RDAgent--1155.org.readthedocs.build/en/1155/
=> docs: update configuration docs

rdagent/scenarios/data_science/dev/feedback.py, rdagent/scenarios/data_science/dev/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--1159.org.readthedocs.build/en/1159/
=> feat: add acceptable assessment in exp_feedback

rdagent/log/ui/ds_summary.py, rdagent/log/ui/ds_trace.py
----
📚 Documentation preview 📚: https://RDAgent--1169.org.readthedocs.build/en/1169/
=> chore: add auto sota selector llm log in trace

rdagent/utils/workflow/loop.py
----
📚 Documentation preview 📚: https://RDAgent--1166.org.readthedocs.build/en/1166/
=> fix: cancel tasks on resume and kill subprocesses on termination

rdagent/utils/workflow/tracking.py
----
📚 Documentation preview 📚: https://RDAgent--1183.org.readthedocs.build/en/1183/
=> chore: catch log_workflow error

rdagent/scenarios/data_science/dev/runner/eval.py
----
📚 Documentation preview 📚: https://RDAgent--1189.org.readthedocs.build/en/1189/
=> fix: skip res_ratio check if timer or res_time is None

rdagent/app/data_science/conf.py, rdagent/scenarios/data_science/scen/__init__.py
----
📚 Documentation preview 📚: https://RDAgent--1196.org.readthedocs.build/en/1196/
=> fix: increase time default not controlled by LLM

README.md, docs/scens/data_copilot_fin.rst, docs/scens/data_science.rst, docs/scens/model_copilot_general.rst, docs/ui.rst, rdagent/scenarios/data_science/example/eval/playground-series-s4e9/grade.py
----
📚 Documentation preview 📚: https://RDAgent--1198.org.readthedocs.build/en/1198/
=> style: convert CLI flags from snake_case to kebab-case

rdagent/log/ui/ds_trace.py
----
📚 Documentation preview 📚: https://RDAgent--1207.org.readthedocs.build/en/1207/
=> fix: ui bug

rdagent/app/kaggle/conf.py, rdagent/components/coder/CoSTEER/__init__.py, rdagent/scenarios/data_science/dev/runner/eval.py, rdagent/utils/workflow/tracking.py
----
📚 Documentation preview 📚: https://RDAgent--1211.org.readthedocs.build/en/1211/
=> feat: add option to enable hyperparameter tuning only in first eval loop

rdagent/scenarios/data_science/loop.py
----
📚 Documentation preview 📚: https://RDAgent--1214.org.readthedocs.build/en/1214/
=> fix: allow prev_out keys to be None in workspace cleanup assertion

rdagent/scenarios/data_science/proposal/exp_gen/merge.py
----
📚 Documentation preview 📚: https://RDAgent--1215.org.readthedocs.build/en/1215/
=> chore: for ui, a simple fix

rdagent/log/ui/ds_trace.py, rdagent/log/ui/utils.py
----
📚 Documentation preview 📚: https://RDAgent--1217.org.readthedocs.build/en/1217/
=> feat: ui, support disable cache

rdagent/scenarios/data_science/dev/runner/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--1223.org.readthedocs.build/en/1223/
=> fix: change runner prompts

rdagent/scenarios/data_science/proposal/exp_gen/proposal.py
----
📚 Documentation preview 📚: https://RDAgent--1230.org.readthedocs.build/en/1230/
=> fix: increase retry count in hypothesis_gen decorator to 10; avaoid alignment error

rdagent/app/cli.py, rdagent/app/data_science/conf.py, rdagent/components/coder/data_science/pipeline/prompts.yaml, rdagent/components/interactor/__init__.py, rdagent/components/workflow/conf.py, rdagent/core/experiment.py, rdagent/core/interactor.py, rdagent/log/ui/ds_user_interact.py, rdagent/oai/utils/embedding.py, rdagent/scenarios/data_science/experiment/experiment.py, rdagent/scenarios/data_science/interactor/__init__.py, rdagent/scenarios/data_science/loop.py, rdagent/scenarios/data_science/proposal/exp_gen/prompts_v2.yaml, rdagent/scenarios/data_science/proposal/exp_gen/proposal.py
----
📚 Documentation preview 📚: https://RDAgent--1251.org.readthedocs.build/en/1251/
=> feat: add user interaction in data science scenario

README.md
----
📚 Documentation preview 📚: https://RDAgent--1252.org.readthedocs.build/en/1252/
=> feat: update README with latest paper acceptance to NeurIPS 2025

rdagent/scenarios/data_science/proposal/exp_gen/merge.py
----
📚 Documentation preview 📚: https://RDAgent--1254.org.readthedocs.build/en/1254/
=> fix: merge candidates
