microsoft/RD-Agent

README.md, docs/development.rst
----
📚 Documentation preview 📚: https://RDAgent--212.org.readthedocs.build/en/212/
=> docs: update demo link

rdagent/components/coder/factor_coder/CoSTEER/evaluators.py
Error when gen_df is None
```bash
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
File "/root/anaconda3/envs/rdagent/lib/python3.10/multiprocessing/pool.py", line 125, in worker
result = (True, func(*args, **kwds))
File "/root/remote/RD-Agent/rdagent/components/coder/factor_coder/CoSTEER/evaluators.py", line 610, in evaluate
) = self.value_evaluator.evaluate(implementation=implementation, gt_implementation=gt_implementation)
File "/root/remote/RD-Agent/rdagent/components/coder/factor_coder/CoSTEER/evaluators.py", line 387, in evaluate
feedback_str, single_column_result = FactorRowCountEvaluator(self.scen).evaluate(
File "/root/remote/RD-Agent/rdagent/components/coder/factor_coder/CoSTEER/evaluators.py", line 249, in …
```
=> fix: check if gen_df is None

rdagent/components/benchmark/eval_method.py, rdagent/scenarios/qlib/factor_experiment_loader/json_loader.py
abort subsequent evaluators for invalid gen_df
----
📚 Documentation preview 📚: https://RDAgent--260.org.readthedocs.build/en/260/
=> fix: eval_method cannot catch run factor error

rdagent/components/coder/factor_coder/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--268.org.readthedocs.build/en/268/
=> fix: actively raised errors are also considered as negative feedback.

rdagent/components/coder/factor_coder/factor_execution_template.txt, rdagent/scenarios/kaggle/experiment/meta_tpl/feature/feature.py, rdagent/scenarios/kaggle/experiment/meta_tpl/train.py, rdagent/scenarios/kaggle/experiment/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--272.org.readthedocs.build/en/272/
=> fix: update new feature engineering code format

rdagent/core/experiment.py, rdagent/scenarios/kaggle/developer/runner.py, rdagent/scenarios/kaggle/experiment/meta_tpl/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/workspace.py, rdagent/scenarios/kaggle/proposal/proposal.py
Fix some bugs in the entire loop.
----
📚 Documentation preview 📚: https://RDAgent--274.org.readthedocs.build/en/274/
=> fix: fix some bugs in the entire loop

rdagent/log/ui/app.py
----
📚 Documentation preview 📚: https://RDAgent--277.org.readthedocs.build/en/277/
=> fix: show variables only when it exists in demo

rdagent/components/coder/factor_coder/CoSTEER/evaluators.py, rdagent/components/coder/factor_coder/factor.py, rdagent/oai/llm_utils.py
----
📚 Documentation preview 📚: https://RDAgent--278.org.readthedocs.build/en/278/
=> fix: support seed and fix absolute path

rdagent/app/kaggle/loop.py, rdagent/app/qlib_rd_loop/factor_from_report.py, rdagent/components/coder/factor_coder/factor.py, rdagent/components/coder/factor_coder/factor_execution_template.txt, rdagent/core/experiment.py, rdagent/core/prompts.py, rdagent/core/utils.py, rdagent/scenarios/data_mining/proposal/model_proposal.py, rdagent/scenarios/kaggle/experiment/meta_tpl/cross_validation_tpl.py, rdagent/scenarios/kaggle/experiment/meta_tpl/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/meta_tpl/model/model_rf.py, rdagent/scenarios/kaggle/experiment/meta_tpl/model/model_xgb.py, rdagent/scenarios/kaggle/experiment/prompts.yaml, rdagent/scenarios/kaggle/experiment/scenario.py, rdagent/scenarios/kaggle/experiment/workspace.py, rdagent/scenarios/kaggle/proposal/proposal.py, rdagent/scenarios/qlib/proposal/factor_proposal.py, rdagent/scenarios/qlib/proposal/model_proposal.py
----
📚 Documentation preview 📚: https://RDAgent--279.org.readthedocs.build/en/279/
=> fix: improve_execution_time_in_kaggle_loop

rdagent/scenarios/kaggle/experiment/meta_tpl/model/model_xgb.py, rdagent/scenarios/kaggle/experiment/meta_tpl/train.py
----
📚 Documentation preview 📚: https://RDAgent--283.org.readthedocs.build/en/283/
=> fix: update train.py to fix a bug in ensemble methods

rdagent/components/coder/model_coder/CoSTEER/evolving_strategy.py, rdagent/components/coder/model_coder/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--284.org.readthedocs.build/en/284/
=> feat: Model context for tuning and selection

rdagent/app/kaggle/conf.py, rdagent/app/kaggle/loop.py, rdagent/scenarios/kaggle/developer/runner.py, rdagent/scenarios/kaggle/experiment/feedback-prize-english-language-learning_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/feedback-prize-english-language-learning_template/feature/feature.py, rdagent/scenarios/kaggle/experiment/feedback-prize-english-language-learning_template/model/model.py, rdagent/scenarios/kaggle/experiment/feedback-prize-english-language-learning_template/train.py, rdagent/scenarios/kaggle/experiment/kaggle_experiment.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e8_template/cross_validation_tpl.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e8_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e8_template/feature/feature.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e8_template/model/model_rf.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e8_template/model/model_xgb.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e8_template/train.py, rdagent/scenarios/kaggle/experiment/scenario.py, rdagent/scenarios/kaggle/experiment/workspace.py, rdagent/scenarios/kaggle/kaggle_crawler.py, rdagent/utils/env.py, test/utils/test_kaggle.py
----
📚 Documentation preview 📚: https://RDAgent--287.org.readthedocs.build/en/287/
=> feat: kaggle templates related

Makefile, rdagent/app/kaggle/conf.py, rdagent/app/kaggle/loop.py, rdagent/components/coder/factor_coder/CoSTEER/knowledge_management.py, rdagent/components/coder/model_coder/CoSTEER/knowledge_management.py, rdagent/components/knowledge_management/graph.py, rdagent/components/knowledge_management/vector_base.py, rdagent/components/workflow/conf.py, rdagent/core/evolving_framework.py, rdagent/core/knowledge_base.py, rdagent/core/prompts.py, rdagent/core/proposal.py, rdagent/oai/llm_utils.py, rdagent/scenarios/kaggle/experiment/meta_tpl/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/prompts.yaml, rdagent/scenarios/kaggle/experiment/scenario.py, rdagent/scenarios/kaggle/experiment/workspace.py, rdagent/scenarios/kaggle/knowledge_management/graph.py, rdagent/scenarios/kaggle/knowledge_management/prompts.yaml, rdagent/scenarios/kaggle/knowledge_management/vector_base.py, rdagent/scenarios/kaggle/prompts.yaml, rdagent/scenarios/kaggle/proposal/proposal.py
----
📚 Documentation preview 📚: https://RDAgent--301.org.readthedocs.build/en/301/
=> feat:  Initial version if Graph RAG in KAGGLE scenario

rdagent/scenarios/kaggle/experiment/forest-cover-type-prediction_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/meta_tpl/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e8_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/playground-series-s4e9_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/scenario.py, rdagent/scenarios/kaggle/experiment/sf-crime_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/spaceship-titanic_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/workspace.py, rdagent/scenarios/kaggle/kaggle_crawler.py
save all independent preprocess generated files (like passenger_ids/ids/encoder... ) to "others.pkl" now.
----
📚 Documentation preview 📚: https://RDAgent--310.org.readthedocs.build/en/310/
=> fix: bug of saving preprocess cache files

rdagent/components/coder/model_coder/model.py, rdagent/utils/env.py
----
📚 Documentation preview 📚: https://RDAgent--311.org.readthedocs.build/en/311/
=> fix: Use fixed file name in model costeer & fixing cache

rdagent/scenarios/kaggle/developer/feedback.py, rdagent/scenarios/kaggle/prompts.yaml
Fix a bug in model tuning feedback.
----
📚 Documentation preview 📚: https://RDAgent--316.org.readthedocs.build/en/316/
=> fix: fix a bug in model tuning feedback

rdagent/scenarios/kaggle/experiment/playground-series-s3e11_template/model/model_randomforest.py
----
📚 Documentation preview 📚: https://RDAgent--347.org.readthedocs.build/en/347/
=> feat: random forest for s3e11

rdagent/app/kaggle/conf.py, rdagent/scenarios/kaggle/developer/feedback.py, rdagent/scenarios/kaggle/experiment/scenario.py, rdagent/scenarios/kaggle/knowledge_management/graph.py, rdagent/scenarios/kaggle/knowledge_management/prompts.yaml, rdagent/scenarios/kaggle/knowledge_management/vector_base.py, rdagent/scenarios/kaggle/prompts.yaml, rdagent/scenarios/kaggle/proposal/proposal.py
Refine some codes.
----
📚 Documentation preview 📚: https://RDAgent--353.org.readthedocs.build/en/353/
=> fix: refine some codes

rdagent/log/ui/app.py, rdagent/scenarios/kaggle/developer/feedback.py, rdagent/scenarios/kaggle/developer/runner.py, rdagent/scenarios/kaggle/experiment/feedback-prize-english-language-learning_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/feedback-prize-english-language-learning_template/feature/feature.py, rdagent/scenarios/kaggle/experiment/feedback-prize-english-language-learning_template/model/model_xgboost.py, rdagent/scenarios/kaggle/experiment/feedback-prize-english-language-learning_template/train.py, rdagent/scenarios/kaggle/experiment/forest-cover-type-prediction_template/train.py, rdagent/scenarios/kaggle/experiment/optiver-realized-volatility-prediction_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/optiver-realized-volatility-prediction_template/feature/feature.py, rdagent/scenarios/kaggle/experiment/optiver-realized-volatility-prediction_template/model/model_xgboost.py, rdagent/scenarios/kaggle/experiment/optiver-realized-volatility-prediction_template/train.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e11_template/train.py, rdagent/scenarios/kaggle/experiment/scenario.py, rdagent/scenarios/kaggle/proposal/proposal.py
Fix some errors in scenario.py, proposal.py and runner.py.
----
📚 Documentation preview 📚: https://RDAgent--365.org.readthedocs.build/en/365/
=> fix: fix some errors in scenario.py, proposal.py and runner.py

rdagent/app/kaggle/loop.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e16_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e16_template/feature/feature.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e16_template/model/model_randomforest.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e16_template/model/model_xgboost.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e16_template/model/select_randomforest.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e16_template/model/select_xgboost.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e16_template/train.py
----
📚 Documentation preview 📚: https://RDAgent--396.org.readthedocs.build/en/396/
=> feat: add kaggle s3e16 template

rdagent/app/kaggle/loop.py, rdagent/components/coder/factor_coder/CoSTEER/evolving_strategy.py, rdagent/components/proposal/model_proposal.py, rdagent/components/proposal/prompts.yaml, rdagent/core/knowledge_base.py, rdagent/scenarios/kaggle/experiment/playground-series-s3e11_template/fea_share_preprocess.py, rdagent/scenarios/kaggle/experiment/scenario.py, rdagent/scenarios/kaggle/knowledge_management/prompts.yaml, rdagent/scenarios/kaggle/knowledge_management/vector_base.py, rdagent/scenarios/kaggle/prompts.yaml, rdagent/scenarios/kaggle/proposal/proposal.py
Fix some bugs in rag.
----
📚 Documentation preview 📚: https://RDAgent--399.org.readthedocs.build/en/399/
=> fix: fix some bugs in rag

README.md, docs/scens/kaggle_agent.rst
----
📚 Documentation preview 📚: https://RDAgent--465.org.readthedocs.build/en/465/
=> docs: correct some mistakes in Kaggle scenario guidance

docs/scens/kaggle_agent.rst, rdagent/components/coder/model_coder/model_execute_template_v2.txt, rdagent/scenarios/kaggle/developer/runner.py
Fix a bug in kaggle runner cache and kaggle costeer execute template.
----
📚 Documentation preview 📚: https://RDAgent--467.org.readthedocs.build/en/467/
=> fix: fix a bug in kaggle runner cache and kaggle costeer execute template

rdagent/app/kaggle/loop.py, rdagent/components/coder/model_coder/CoSTEER/evaluators.py, rdagent/components/knowledge_management/graph.py, rdagent/components/proposal/__init__.py, rdagent/components/runner/__init__.py, rdagent/core/experiment.py, rdagent/core/utils.py, rdagent/log/ui/app.py, rdagent/scenarios/kaggle/developer/feedback.py, rdagent/scenarios/kaggle/developer/runner.py, rdagent/scenarios/kaggle/docker/kaggle_docker/Dockerfile, rdagent/scenarios/kaggle/docker/mle_bench_docker/Dockerfile, rdagent/scenarios/kaggle/experiment/prompts.yaml, rdagent/scenarios/kaggle/experiment/scenario.py, rdagent/scenarios/kaggle/experiment/sf-crime_template/train.py, rdagent/scenarios/kaggle/experiment/spaceship-titanic_template/train.py, rdagent/scenarios/kaggle/experiment/tabular-playground-series-may-2022_template/model/model_xgboost.py, rdagent/scenarios/kaggle/experiment/tabular-playground-series-may-2022_template/model/select_lightgbm.py, rdagent/scenarios/kaggle/experiment/tabular-playground-series-may-2022_template/train.py, rdagent/scenarios/kaggle/experiment/ventilator-pressure-prediction_template/model/select_lightgbm.py, rdagent/scenarios/kaggle/experiment/ventilator-pressure-prediction_template/train.py, rdagent/scenarios/kaggle/kaggle_crawler.py, rdagent/scenarios/kaggle/prompts.yaml, rdagent/scenarios/kaggle/proposal/proposal.py, rdagent/utils/env.py
----
📚 Documentation preview 📚: https://RDAgent--477.org.readthedocs.build/en/477/
=> feat: align mlebench data and evaluation & several fix on kaggle workflow

docs/_static/RD2bench.json, docs/research/benchmark.rst, rdagent/app/benchmark/factor/analysis.py, rdagent/app/benchmark/factor/eval.py, rdagent/components/benchmark/conf.py, rdagent/components/coder/factor_coder/eva_utils.py, rdagent/components/coder/factor_coder/evolving_strategy.py
----
📚 Documentation preview 📚: https://RDAgent--497.org.readthedocs.build/en/497/
=> feat: run benchmark on gpt-4o & llama 3.1

.github/PULL_REQUEST_TEMPLATE.md, README.md, docs/installation_and_configuration.rst, rdagent/app/cli.py, rdagent/app/general_model/general_model.py, rdagent/app/utils/health_check.py, rdagent/log/ui/app.py
----
📚 Documentation preview 📚: https://RDAgent--487.org.readthedocs.build/en/487/
=> chore: fix PR template

rdagent/oai/llm_utils.py, rdagent/utils/env.py, rdagent/utils/workflow.py
----
📚 Documentation preview 📚: https://RDAgent--573.org.readthedocs.build/en/573/
=> fix: add retry mechanism for GPU device check in DockerEnv

rdagent/scenarios/data_science/proposal/exp_gen.py, rdagent/scenarios/data_science/proposal/prompts.yaml
Improve the framework's ability to adaptively adjust the model.
----
📚 Documentation preview 📚: https://RDAgent--629.org.readthedocs.build/en/629/
=> feat: improve the framework's ability to adaptively adjust the model

rdagent/components/coder/data_science/ensemble/eval_tests/ensemble_test.txt, rdagent/components/coder/data_science/model/prompts.yaml, rdagent/scenarios/data_science/proposal/prompts.yaml
----
📚 Documentation preview 📚: https://RDAgent--648.org.readthedocs.build/en/648/
=> fix: fix some bugs (ensemble output, HPO, model tuning)

rdagent/oai/backend/base.py, rdagent/scenarios/data_science/proposal/exp_gen.py
----
📚 Documentation preview 📚: https://RDAgent--662.org.readthedocs.build/en/662/
=> fix: target json type & round

rdagent/log/mle_summary.py
Add rank into report (mle_summary).
----
📚 Documentation preview 📚: https://RDAgent--665.org.readthedocs.build/en/665/
=> feat: add rank into report (mle_summary)

rdagent/core/experiment.py, rdagent/utils/__init__.py, rdagent/utils/prompts.yaml
Fix a bug in progress_bar filter.
----
📚 Documentation preview 📚: https://RDAgent--712.org.readthedocs.build/en/712/
=> fix: fix a bug in progress_bar filter

.readthedocs.yaml
----
📚 Documentation preview 📚: https://RDAgent--711.org.readthedocs.build/en/711/
=> fix: fix docs build error

README.md, docs/installation_and_configuration.rst, rdagent/oai/backend/litellm.py
We support using LiteLLM as LLM-Backend to use various model more flexibly.
----
📚 Documentation preview 📚: https://RDAgent--703.org.readthedocs.build/en/703/
=> docs: update readme and installation guide for litellm backend addition

rdagent/components/coder/data_science/ensemble/eval_tests/ensemble_test.txt
----
📚 Documentation preview 📚: https://RDAgent--739.org.readthedocs.build/en/739/
=> fix: replace func "len()" in ensemble test code to support various data type

rdagent/core/proposal.py, rdagent/scenarios/data_science/loop.py, rdagent/scenarios/data_science/proposal/exp_gen/base.py, rdagent/scenarios/data_science/proposal/exp_gen/ckp_select.py, rdagent/scenarios/data_science/proposal/exp_gen/merge.py, rdagent/scenarios/data_science/proposal/exp_gen/merge.yaml, rdagent/scenarios/data_science/proposal/exp_gen/proposal.py, rdagent/utils/__init__.py
----
📚 Documentation preview 📚: https://RDAgent--888.org.readthedocs.build/en/888/
=> feat: merge selectively

.env.example, README.md, docs/installation_and_configuration.rst, rdagent/oai/llm_conf.py, test/oai/test_embedding_and_similarity.py
----
📚 Documentation preview 📚: https://RDAgent--958.org.readthedocs.build/en/958/
=> docs: update explanation for separate config use in litellm

rdagent/scenarios/data_science/loop.py
The bug was caused by the wrong calling order of "self.trace.sync_dag_parent_and_hist()" and "self.trace.hist.append" in rdagent/scenarios/data_science/loop.py, the record() method of class DataScienceRDLoop.
The correct order should be "self.trace.sync_dag_parent_and_hist()" first, then "self.trace.hist.append", but in the **feat: async mechanism for multi-trace #981**, it get inversed. Now we fix it
----
📚 Documentation preview 📚: https://RDAgent--996.org.readthedocs.build/en/996/
=> fix: handle the bug of wrong dag_parant index

rdagent/oai/backend/base.py, rdagent/oai/backend/deprec.py, rdagent/oai/backend/litellm.py, rdagent/oai/llm_conf.py, rdagent/scenarios/data_science/proposal/exp_gen/proposal.py
----
📚 Documentation preview 📚: https://RDAgent--1038.org.readthedocs.build/en/1038/
=> fix: based on response schema; not function calling

rdagent/components/coder/data_science/conf.py, rdagent/components/coder/data_science/pipeline/__init__.py, rdagent/components/coder/data_science/pipeline/prompts.yaml, rdagent/scenarios/data_science/dev/runner/__init__.py, rdagent/scenarios/data_science/proposal/exp_gen/naive.py, rdagent/scenarios/data_science/proposal/exp_gen/prompts_v2.yaml
----
📚 Documentation preview 📚: https://RDAgent--1034.org.readthedocs.build/en/1034/
=> fix: split then sample & remove simple model guide in ds proposal

rdagent/components/coder/CoSTEER/config.py, rdagent/scenarios/data_science/proposal/exp_gen/prompts_v2.yaml, rdagent/scenarios/data_science/proposal/exp_gen/proposal.py, rdagent/scenarios/data_science/scen/__init__.py, rdagent/scenarios/data_science/scen/prompts.yaml, rdagent/utils/env.py
- Updated config.py to support debug timeout configuration
- Synchronized prompts in exp_gen and scen modules
- Refactored proposal.py for consistency with new scenario descriptions
- Improved __init__.py for better scenario management
----
📚 Documentation preview 📚: https://RDAgent--1079.org.readthedocs.build/en/1079/
=> fix: align scenario descriptions and include debug timeout

rdagent/components/coder/data_science/pipeline/prompts.yaml, rdagent/scenarios/data_science/proposal/exp_gen/utils.py
----
📚 Documentation preview 📚: https://RDAgent--1092.org.readthedocs.build/en/1092/
=> fix: package and timer bug

rdagent/scenarios/data_science/proposal/exp_gen/select/prompts.yaml, rdagent/scenarios/data_science/share.yaml
new prompt for auto-sota-selector:
- add detailed criterias on generalizability and risk of overfitting
- add special & additional principles for pretrained models + fine-tuning cases
----
📚 Documentation preview 📚: https://RDAgent--1109.org.readthedocs.build/en/1109/
=> feat: new prompt for auto-sota-selector

rdagent/app/kaggle/conf.py, rdagent/scenarios/data_science/dev/runner/eval.py
----
📚 Documentation preview 📚: https://RDAgent--1175.org.readthedocs.build/en/1175/
=> feat: refine the logic of enabling hyperparameter tuning and add criteira

rdagent/components/coder/data_science/ensemble/eval.py, rdagent/components/coder/data_science/feature/eval.py, rdagent/components/coder/data_science/model/eval.py, rdagent/components/coder/data_science/pipeline/eval.py, rdagent/components/coder/data_science/raw_data_loader/eval.py, rdagent/components/coder/data_science/workflow/eval.py, rdagent/core/experiment.py, rdagent/scenarios/data_science/dev/runner/__init__.py, rdagent/scenarios/data_science/dev/runner/eval.py, rdagent/scenarios/data_science/proposal/exp_gen/select/submit.py, rdagent/utils/env.py
----
📚 Documentation preview 📚: https://RDAgent--1236.org.readthedocs.build/en/1236/
=> feat: add stdout into workspace for easier debugging
